/* Zusätzliche Grammatikaufgaben zum Madina-Buch: Verständnisfragen je Lektion („Warum …?“,
   „Finde den Fehler“, „Welche Rolle hat …?“). Je Frage: q, a (a[0] richtig), e = Erklärung,
   w = drei Gründe, warum a[1], a[2], a[3] falsch sind. arabic.js hängt sie an die Grammatik der Lektion an. */
window.MADINA_PLUS = {
"m01": [
 {"q":"Warum steht in هَذَا بَيْتٌ kein Wort für „ist“?","a":["Im Nominalsatz wird „ist“ nicht ausgedrückt.","Weil هَذَا „ist“ bedeutet.","Weil das Tanwīn „ist“ bedeutet.","Weil der Satz eine Frage ist."],"e":"Subjekt + Prädikat genügen: هَذَا بَيْتٌ = „Dies (ist) ein Haus“.","w":["هَذَا heißt „dies“, es ist das Subjekt.","Das Tanwīn entspricht „ein“, nicht „ist“.","Der Satz ist eine Aussage; eine Frage bräuchte أَ oder ein Fragewort."]},
 {"q":"Finde den Fehler: مَنْ هَذَا؟ هَذَا قَلَمٌ.","a":["مَنْ fragt nach Personen, ein Stift ist eine Sache: مَا هَذَا؟","قَلَمٌ braucht den Artikel.","هَذَا muss هَذِهِ heißen.","Es gibt keinen Fehler."],"e":"Nach Sachen fragt man mit مَا, nach Personen mit مَنْ.","w":["„ein Stift“ ist unbestimmt; das Tanwīn ist richtig.","قَلَمٌ ist männlich, also هَذَا.","Doch: Nach einem Stift fragt man nicht mit „wer“."]},
 {"q":"Was macht aus einer Aussage eine Ja/Nein-Frage?","a":["أَ vor dem Satz","ein Tanwīn am Ende","مَنْ am Satzende","لَا vor dem Satz"],"e":"أَهَذَا بَيْتٌ؟ – „Ist das ein Haus?“","w":["Das Tanwīn macht ein Wort unbestimmt, keine Frage.","مَنْ ist ein Fragewort „wer“ und steht vorne.","لَا heißt „nein“ bzw. verneint."]},
 {"q":"Warum sagt man بَيْتٌ und nicht einfach بَيْت, wenn man „ein Haus“ meint?","a":["Das Tanwīn (-un) ist das Zeichen der Unbestimmtheit.","Das -un zeigt den Plural.","Das -un zeigt, dass es eine Frage ist.","Das -un ist nur Verzierung."],"e":"Im Arabischen gibt es kein eigenes Wort für „ein“; das Tanwīn übernimmt diese Aufgabe.","w":["Der Plural von بَيْتٌ ist بُيُوتٌ.","Fragen bildet man mit أَ oder Fragewörtern.","Das Tanwīn hat eine Bedeutung: „ein“."]}
],
"m02": [
 {"q":"Wann verwendet man ذَلِكَ statt هَذَا?","a":["für etwas Entferntes","für etwas Weibliches","für Personen","für den Plural"],"e":"هَذَا = dies (nah), ذَلِكَ = jenes (fern).","w":["Weiblich wären هَذِهِ bzw. تِلْكَ.","Beide stehen für Personen und Sachen.","ذَلِكَ ist Singular."]},
 {"q":"Warum schreibt man وَذَلِكَ in einem Wort?","a":["وَ besteht nur aus einem Buchstaben und wird immer angehängt.","Weil ذَلِكَ weiblich ist.","Weil es ein Name ist.","Das ist nur bei ذَلِكَ so."],"e":"Einbuchstabige Wörter wie وَ, بِـ, لِـ werden an das folgende Wort geschrieben.","w":["ذَلِكَ ist männlich.","ذَلِكَ ist kein Name.","Das gilt für jedes Wort nach وَ."]},
 {"q":"Was ist in ذَلِكَ مَسْجِدٌ das Subjekt?","a":["ذَلِكَ","مَسْجِدٌ","das Tanwīn","Es gibt keins."],"e":"ذَلِكَ ist das Mubtadaʾ, مَسْجِدٌ das Khabar.","w":["مَسْجِدٌ ist die Aussage über ذَلِكَ.","Das Tanwīn ist ein Zeichen, kein Wort.","Jeder Nominalsatz hat ein Subjekt."]}
],
"m03": [
 {"q":"Warum sagt man ar-rajulu und nicht al-rajulu?","a":["ر ist ein Sonnenbuchstabe; das l gleicht sich an.","ر ist ein Mondbuchstabe.","Weil رَجُلٌ männlich ist.","Das ist Dialekt."],"e":"Vor Sonnenbuchstaben wird das l von al nicht gesprochen; der Buchstabe wird verdoppelt (Shadda).","w":["Bei Mondbuchstaben bleibt das l hörbar (al-qamaru).","Das Geschlecht hat mit der Aussprache nichts zu tun.","Das ist Hochsprache, eine feste Regel."]},
 {"q":"Warum fällt das Tanwīn weg, wenn الْ davorsteht?","a":["Tanwīn heißt „ein“, الْ heißt „der“ – beides zugleich geht nicht.","Weil das Wort dann weiblich wird.","Weil das Wort im Genitiv steht.","Das Tanwīn bleibt."],"e":"Unbestimmt (Tanwīn) und bestimmt (الْ) schließen sich aus: بَيْتٌ – الْبَيْتُ.","w":["Der Artikel ändert das Geschlecht nicht.","Der Fall bleibt; nur das Tanwīn fällt weg.","Es heißt الْبَيْتُ, nicht الْبَيْتٌ."]},
 {"q":"Welcher Satz ist ein vollständiger Satz?","a":["الْبَيْتُ كَبِيرٌ","الْبَيْتُ الْكَبِيرُ","بَيْتٌ كَبِيرٌ","الْكَبِيرُ الْبَيْتُ"],"e":"Bestimmtes Subjekt + unbestimmtes Prädikat = Satz: „Das Haus ist groß.“","w":["Beide bestimmt: „das große Haus“ – kein Satz.","Beide unbestimmt: „ein großes Haus“ – kein Satz.","Das Adjektiv steht nicht vor dem Nomen."]},
 {"q":"Was passiert mit dem a von الْ in وَالْبَيْتُ?","a":["Es fällt in der Aussprache weg: wa-l-baitu.","Es wird lang: wā-al-baitu.","Es wird zu i: wi-l-baitu.","Es bleibt: wa al-baitu."],"e":"Das a von al ist ein Hamzatu l-waṣl und wird nur am Satzanfang gesprochen.","w":["Es wird nicht verlängert, sondern fällt weg.","Es wird nicht zu i.","Nach einem Wort wird es nicht gesprochen."]}
],
"m04": [
 {"q":"Woran erkennt man in فِي الْبَيْتِ, dass الْبَيْتِ im Genitiv steht?","a":["an der Endung -i (Kasra)","am Artikel الْ","am Buchstaben ي","am Tanwīn"],"e":"Nach einer Präposition steht der Genitiv; sein Zeichen ist die Kasra.","w":["Den Artikel hat das Wort in jedem Fall.","ي gehört nicht zu الْبَيْتِ; die Endung ist ein Vokal.","Mit الْ gibt es kein Tanwīn."]},
 {"q":"Warum fragt man nach السَّاعَةُ mit أَيْنَ هِيَ؟ und nicht mit هُوَ?","a":["السَّاعَةُ ist grammatisch weiblich.","Weil es eine Sache ist.","Weil es eine Frage ist.","Weil ة „sie“ bedeutet."],"e":"Pronomen richten sich nach dem grammatischen Geschlecht, auch bei Sachen.","w":["Auch männliche Sachen bekommen هُوَ (الْكِتَابُ → هُوَ).","Die Frage bestimmt nicht das Pronomen.","ة ist nur das Kennzeichen des Weiblichen."]},
 {"q":"Welches Wort steht im Genitiv? الْكِتَابُ عَلَى الْمَكْتَبِ","a":["الْمَكْتَبِ","الْكِتَابُ","عَلَى","keines"],"e":"Nach عَلَى steht der Genitiv: الْمَكْتَبِ mit -i.","w":["الْكِتَابُ hat -u: Nominativ, Subjekt.","عَلَى ist eine Präposition ohne Fall.","Doch: الْمَكْتَبِ nach der Präposition."]},
 {"q":"Warum hat آمِنَةُ kein Tanwīn?","a":["Weibliche Eigennamen bekommen kein Tanwīn.","Weil es mit الْ steht.","Weil es im Genitiv steht.","Weil es ein Plural ist."],"e":"Weibliche Namen sind Diptota: آمِنَةُ، فَاطِمَةُ، زَيْنَبُ.","w":["آمِنَةُ hat keinen Artikel.","Es steht im Nominativ (-u).","Es ist ein einzelner Name."]}
],
"m04a": [
 {"q":"Warum wird مِنْ vor الْمَسْجِدِ zu مِنَ?","a":["Zwei vokallose Laute (n + l) treffen aufeinander; der Hilfsvokal ist a.","Weil مَسْجِدٌ männlich ist.","Weil danach der Genitiv kommt.","Weil مِنْ dann „aus“ heißt."],"e":"Vor dem Artikel bekommt das n von مِنْ ein Fatḥa: mina l-masjidi.","w":["Das Geschlecht spielt keine Rolle.","Der Genitiv kommt nach jeder Präposition, das ändert مِنْ nicht.","مِنْ heißt immer „von, aus“."]},
 {"q":"Was ist der Unterschied zwischen einem Nominal- und einem Verbalsatz?","a":["Der Verbalsatz beginnt mit einem Verb, der Nominalsatz mit einem Nomen.","Der Verbalsatz hat kein Subjekt.","Der Nominalsatz ist immer eine Frage.","Es gibt keinen Unterschied."],"e":"ذَهَبَ بِلَالٌ (Verbalsatz) – بِلَالٌ طَالِبٌ (Nominalsatz).","w":["Auch der Verbalsatz hat ein Subjekt (Fāʿil).","Beide können Aussage oder Frage sein.","Doch: Das erste Wort entscheidet."]},
 {"q":"In ذَهَبَ بِلَالٌ – wo ist das „er“ aus ذَهَبَ („er ging“)?","a":["Es entfällt, weil das Subjekt بِلَالٌ genannt ist.","Es steckt im Tanwīn von بِلَالٌ.","Man müsste هُوَ ergänzen.","Es ist das Objekt."],"e":"Steht das Subjekt dabei, braucht das Verb kein eigenes „er“.","w":["Das Tanwīn heißt „ein“, nicht „er“.","ذَهَبَ هُوَ بِلَالٌ wäre falsch.","Es gibt hier kein Objekt."]},
 {"q":"Warum steht nach إِلَى der Genitiv: إِلَى السُّوقِ?","a":["إِلَى ist eine Präposition, und nach Präpositionen steht immer der Genitiv.","Weil السُّوقُ weiblich ist.","Weil es ein Ort ist.","Weil ein Verb davorsteht."],"e":"Jede Präposition (فِي، عَلَى، مِنْ، إِلَى …) verlangt den Genitiv.","w":["Das Geschlecht bestimmt den Fall nicht.","Nicht der Ort, sondern die Präposition bestimmt den Fall.","Das Verb regiert hier nicht السُّوقِ."]}
],
"m05": [
 {"q":"Warum hat كِتَابُ in كِتَابُ بِلَالٍ weder الْ noch Tanwīn?","a":["Es ist Muḍāf und wird durch den Besitzer bestimmt.","Weil es im Nominativ steht.","Weil بِلَالٌ ein Name ist.","Das ist ein Fehler."],"e":"Der Muḍāf ist durch die Iḍāfa bestimmt; deshalb verliert er Artikel und Tanwīn.","w":["Im Nominativ hätte ein normales Wort Tanwīn.","Auch bei كِتَابُ الطَّالِبِ fehlt Artikel und Tanwīn.","Das ist die Regel der Iḍāfa."]},
 {"q":"Welche Übersetzung passt zu بَيْتُ الْمُدَرِّسِ?","a":["das Haus des Lehrers","ein Haus eines Lehrers","Das Haus ist ein Lehrer.","der Lehrer des Hauses"],"e":"Das erste Wort ist das Besessene, das zweite der Besitzer.","w":["الْمُدَرِّسِ ist bestimmt, also ist auch das Ganze bestimmt.","Die Iḍāfa ist kein Satz.","Die Reihenfolge ist umgekehrt."]},
 {"q":"Welches Wort ist in سَيَّارَةُ الْمُدِيرِ der Muḍāf ilaihi?","a":["الْمُدِيرِ","سَيَّارَةُ","beide","keines"],"e":"Der Muḍāf ilaihi ist der Besitzer und steht im Genitiv (-i).","w":["سَيَّارَةُ ist der Muḍāf.","Die zwei Glieder haben verschiedene Rollen.","Jede Iḍāfa hat einen Muḍāf ilaihi."]},
 {"q":"Warum heißt es يَا بِلَالُ und nicht يَا بِلَالٌ?","a":["Der angerufene Name bekommt nur eine einfache Ḍamma.","Weil يَا den Genitiv verlangt.","Weil بِلَالٌ weiblich ist.","Beides ist richtig."],"e":"Der Munādā (Eigenname) ist mabnī auf Ḍamma, ohne Tanwīn.","w":["Dann stünde -i, nicht -u.","بِلَالٌ ist männlich.","Nach يَا fällt das Tanwīn weg."]}
],
"m06": [
 {"q":"Warum sagt man هَذِهِ عَيْنٌ und nicht هَذَا عَيْنٌ?","a":["عَيْنٌ ist weiblich (paariger Körperteil), obwohl es kein ة hat.","Weil عَيْنٌ im Genitiv steht.","Weil es ein Plural ist.","Beides ist richtig."],"e":"Paarige Körperteile sind meist weiblich: عَيْنٌ، يَدٌ، رِجْلٌ، أُذُنٌ.","w":["عَيْنٌ hat -un: Nominativ.","عَيْنٌ ist Singular.","Das Demonstrativ muss zum Geschlecht passen."]},
 {"q":"Was bedeutet لِـ in هَذَا لِبِلَالٍ?","a":["„gehört“ – Besitz","„und“","„nicht“","„in“"],"e":"هَذَا لِبِلَالٍ – „Das gehört Bilāl.“ Danach Genitiv.","w":["„und“ ist وَ.","„nicht“ ist لَا.","„in“ ist فِي."]},
 {"q":"Warum schreibt man لِلْمُدَرِّسِ ohne das Alif von الْ?","a":["Das Alif von الْ fällt nach لِـ in der Schrift weg.","Weil مُدَرِّسٌ männlich ist.","Weil das Wort im Genitiv steht.","Das ist ein Druckfehler."],"e":"لِـ + الْمُدَرِّسِ → لِلْمُدَرِّسِ.","w":["Das Geschlecht spielt keine Rolle.","Den Genitiv gibt es auch nach فِي, dort bleibt das Alif.","Das ist eine feste Schreibregel."]},
 {"q":"Welche weibliche Form ist unregelmäßig (ohne ة gebildet)?","a":["ابْنٌ → بِنْتٌ","مُدَرِّسٌ → مُدَرِّسَةٌ","طَالِبٌ → طَالِبَةٌ","مُسْلِمٌ → مُسْلِمَةٌ"],"e":"Manche Wörter haben eigene weibliche Formen: ابْنٌ – بِنْتٌ, أَخٌ – أُخْتٌ.","w":["مُدَرِّسَةٌ ist regelmäßig mit ة.","طَالِبَةٌ ist regelmäßig mit ة.","مُسْلِمَةٌ ist regelmäßig mit ة."]}
],
"m07": [
 {"q":"Welches Demonstrativ passt? … سَاعَةٌ (weit weg).","a":["تِلْكَ","ذَلِكَ","هَذِهِ","هَذَا"],"e":"Weiblich und fern → تِلْكَ.","w":["ذَلِكَ ist männlich.","هَذِهِ ist nah.","هَذَا ist männlich und nah."]},
 {"q":"Welche Tabelle ist richtig?","a":["nah: هَذَا / هَذِهِ – fern: ذَلِكَ / تِلْكَ","nah: ذَلِكَ / تِلْكَ – fern: هَذَا / هَذِهِ","männlich: هَذِهِ / تِلْكَ – weiblich: هَذَا / ذَلِكَ","alle vier bedeuten dasselbe"],"e":"m. nah هَذَا, w. nah هَذِهِ, m. fern ذَلِكَ, w. fern تِلْكَ.","w":["Nah und fern sind vertauscht.","Männlich und weiblich sind vertauscht.","Sie unterscheiden sich in Nähe und Geschlecht."]},
 {"q":"Was ist in تِلْكَ سَيَّارَةٌ das Khabar?","a":["سَيَّارَةٌ","تِلْكَ","das ة","Es gibt keins."],"e":"تِلْكَ ist das Subjekt, سَيَّارَةٌ die Aussage.","w":["تِلْكَ ist das Mubtadaʾ.","ة ist ein Buchstabe, kein Satzteil.","Jeder Nominalsatz hat ein Khabar."]}
],
"m08": [
 {"q":"Was ist der Unterschied zwischen هَذَا كِتَابٌ und هَذَا الْكِتَابُ?","a":["Das erste ist ein Satz („Das ist ein Buch“), das zweite nur „dieses Buch“.","Beide bedeuten „Das ist ein Buch“.","Das zweite ist eine Frage.","Das erste ist „dieses Buch“, das zweite ein Satz."],"e":"Mit الْ gehört das Nomen zum Demonstrativ; es fehlt noch das Prädikat.","w":["Der Artikel verändert die Bedeutung: „dieses Buch“.","Eine Frage bräuchte أَ oder ein Fragewort.","Genau umgekehrt."]},
 {"q":"Wie wird هَذَا الْكِتَابُ zu einem vollständigen Satz?","a":["Man ergänzt ein Prädikat: هَذَا الْكِتَابُ جَدِيدٌ.","Man streicht den Artikel nicht, sondern setzt ein Tanwīn dazu.","Man stellt الْكِتَابُ vor هَذَا.","Man hängt ة an."],"e":"„Dieses Buch ist neu“ – جَدِيدٌ ist das Khabar.","w":["الْ und Tanwīn gehen nicht zusammen.","Das Demonstrativ steht vorne.","ة macht ein Wort weiblich, keinen Satz."]},
 {"q":"Warum ändert الْمُسْتَشْفَى seine Endung nie?","a":["Es endet auf langes ā (ى); darauf kann man keinen Endvokal sprechen.","Weil es weiblich ist.","Weil es ein Fremdwort ist.","Weil es immer im Genitiv steht."],"e":"Wörter auf -ā bleiben gleich; die Fallendung ist nur gedacht.","w":["Weibliche Wörter ändern ihre Endung normal (السَّاعَةُ، السَّاعَةِ).","مُسْتَشْفًى ist ein arabisches Wort.","Es kann in jedem Fall stehen."]},
 {"q":"Welcher Fall folgt auf خَلْفَ und أَمَامَ?","a":["Genitiv","Nominativ","Akkusativ","gar keiner"],"e":"خَلْفَ الْمَسْجِدِ, أَمَامَ الْمُدَرِّسِ – das folgende Nomen ist Muḍāf ilaihi.","w":["Den Nominativ hat nur das Wort selbst nie; das folgende Nomen steht im Genitiv.","خَلْفَ/أَمَامَ selbst haben Fatḥa, das Nomen danach Kasra.","Das folgende Nomen hat eine Genitivendung."]}
],
"m09": [
 {"q":"In welchen drei Punkten stimmt das Adjektiv mit seinem Nomen überein (Buch 1)?","a":["Geschlecht, Bestimmtheit und Fall","nur im Geschlecht","nur im Fall","gar nicht"],"e":"بِنْتٌ صَغِيرَةٌ – الْمُدَرِّسُ الْجَدِيدُ – فِي بَيْتٍ جَدِيدٍ.","w":["Auch Bestimmtheit und Fall müssen passen.","Auch Geschlecht und Bestimmtheit müssen passen.","Das Adjektiv folgt immer seinem Nomen."]},
 {"q":"Finde den Fehler: الْبِنْتُ الصَّغِيرُ","a":["Das Adjektiv muss weiblich sein: الصَّغِيرَةُ.","Das Adjektiv braucht Tanwīn.","الْبِنْتُ braucht Tanwīn.","Kein Fehler."],"e":"Das Adjektiv folgt dem Nomen im Geschlecht.","w":["Mit الْ gibt es kein Tanwīn; das Adjektiv muss bestimmt bleiben.","الْبِنْتُ hat den Artikel, also kein Tanwīn.","Doch: بِنْتٌ ist weiblich."]},
 {"q":"Warum bekommt كَسْلَانُ kein Tanwīn?","a":["Adjektive nach dem Muster faʿlān sind Diptota.","Weil es weiblich ist.","Weil es bestimmt ist.","Weil es im Genitiv steht."],"e":"كَسْلَانُ، جَوْعَانُ، عَطْشَانُ، غَضْبَانُ – alle ohne Tanwīn.","w":["كَسْلَانُ ist männlich.","Es ist unbestimmt; trotzdem ohne Tanwīn.","Die Regel gilt in jedem Fall."]},
 {"q":"Welches Relativpronomen passt? الرَّجُلُ … فِي الْمَسْجِدِ إِمَامٌ.","a":["الَّذِي","الَّتِي","هَذَا","مَنْ"],"e":"Männlicher Bezug → الَّذِي: „Der Mann, der in der Moschee ist, ist ein Imam.“","w":["الَّتِي ist für Weibliches.","هَذَا heißt „dies“, kein Relativpronomen.","مَنْ ist hier ein Fragewort."]}
],
"m10": [
 {"q":"Warum fällt in كِتَابُكَ das Tanwīn weg?","a":["Das Nomen ist mit dem Pronomen verbunden (Muḍāf) und dadurch bestimmt.","Weil ـكَ ein Verb ist.","Weil es im Genitiv steht.","Weil كِتَابٌ weiblich ist."],"e":"Ein angehängtes Besitzpronomen macht das Nomen zum Muḍāf.","w":["ـكَ ist ein Pronomen („dein“).","كِتَابُكَ steht im Nominativ.","كِتَابٌ ist männlich."]},
 {"q":"Warum sagt man أَبُوكَ, aber أَبِي?","a":["أَبٌ gehört zu den fünf Nomen und bekommt als Muḍāf ein langes ū – außer vor ـِي.","Weil ـكَ männlich ist.","Weil أَبِي Genitiv ist.","Beides ist unregelmäßig ohne Regel."],"e":"أَبُوكَ، أَبُوهُ، أَبُو مُحَمَّدٍ – aber vor „mein“: أَبِي.","w":["Auch zu einer Frau: أَبُوكِ.","أَبِي steht hier im Nominativ; vor ـِي gibt es kein و.","Es gibt eine Regel: die fünf Nomen."]},
 {"q":"Wann benutzt man لِـ und wann عِنْدَ für „haben“?","a":["لِـ für Verwandte und Körperteile, عِنْدَ für trennbaren Besitz","لِـ für Sachen, عِنْدَ für Personen","Beide sind immer austauschbar.","لِـ nur für Frauen"],"e":"لِي أَخٌ – „ich habe einen Bruder“; عِنْدِي قَلَمٌ – „ich habe einen Stift“.","w":["Genau umgekehrt.","Das Buch unterscheidet sie nach Art des Besitzes.","لِـ gilt für alle Personen."]},
 {"q":"Was verneint مَا in مَا عِنْدِي سَيَّارَةٌ?","a":["den Besitz: „Ich habe kein Auto.“","Es fragt: „Was habe ich?“","Es heißt „nur“.","Es heißt „wie schön“."],"e":"مَا kann auch verneinen.","w":["Ohne Fragezeichen und Antwort ist es eine Verneinung.","„nur“ ist إِنَّمَا.","Staunen bräuchte مَا أَفْعَلَ."]}
],
"m11": [
 {"q":"Warum steht in أُحِبُّ الرَّسُولَ am Ende ein -a?","a":["الرَّسُولَ ist Objekt und steht im Akkusativ.","Weil es bestimmt ist.","Weil ein Prophet gemeint ist.","Weil es nach einer Präposition steht."],"e":"Das Mafʿūl bihi steht im Akkusativ (-a).","w":["Auch bestimmte Subjekte haben -u.","Die Bedeutung bestimmt nicht den Fall.","Nach Präpositionen steht -i."]},
 {"q":"Warum sieht man in أُحِبُّ أَبِي kein -a?","a":["Vor dem ـِي „mein“ kann kein Fallvokal erscheinen; er ist nur gedacht.","Weil أَبِي Subjekt ist.","Weil أَبٌ unveränderlich ist.","Das ist ein Fehler."],"e":"Das Objekt steht trotzdem im Akkusativ, nur unsichtbar.","w":["Das Subjekt ist „ich“ im Verb.","أَبٌ ändert sich sonst (أَبُوكَ، أَبَاكَ).","Das ist richtig so."]},
 {"q":"Wie zählt man im Arabischen „Vater, Mutter und Bruder“ auf?","a":["أَبِي وَأُمِّي وَأَخِي – وَ vor jedem Glied","أَبِي، أُمِّي وَأَخِي – wie im Deutschen","أَبِي أُمِّي أَخِي – ohne وَ","وَأَبِي أُمِّي أَخِي"],"e":"Im Arabischen steht وَ vor jedem weiteren Glied.","w":["Das deutsche Komma-Muster ist im Arabischen unüblich.","Ohne وَ sind die Glieder nicht verbunden.","وَ steht nicht vor dem ersten Glied."]},
 {"q":"Wann fragt man mit مَاذَا statt مَا?","a":["vor einem Verb","vor einem Nomen","bei Personen","nur im Plural"],"e":"مَاذَا تُحِبُّ؟ – aber مَا هَذَا؟","w":["Vor einem Nomen steht مَا.","Nach Personen fragt man mit مَنْ.","مَاذَا gilt in jeder Zahl."]}
],
"m12": [
 {"q":"Welche Endung zeigt „dein“ zu einer Frau?","a":["ـكِ","ـكَ","ـهَا","ـكُمْ"],"e":"بَيْتُكِ – dein (w.) Haus; بَيْتُكَ – dein (m.) Haus.","w":["ـكَ ist für einen Mann.","ـهَا heißt „ihr“.","ـكُمْ heißt „euer“."]},
 {"q":"Warum wird ذَهَبَتْ vor الْبِنْتُ zu ذَهَبَتِ?","a":["Zwei Sukūn (t + l) treffen aufeinander; das t bekommt Kasra.","Weil الْبِنْتُ im Genitiv steht.","Weil الْبِنْتُ weiblich ist.","Weil es eine Frage ist."],"e":"Hilfsvokal gegen zwei Vokallose hintereinander.","w":["الْبِنْتُ steht im Nominativ (Fāʿil).","Weiblich zeigt das t, nicht die Kasra.","Es ist eine Aussage."]},
 {"q":"Warum steht in ذَهَبَتْ مَرْيَمُ kein zusätzliches „sie“ (هِيَ)?","a":["Das Subjekt مَرْيَمُ steht schon da; das -t zeigt nur weiblich an.","Weil مَرْيَمُ ein Name ist.","Weil هِيَ nie vorkommt.","Weil der Satz Plural ist."],"e":"Das تْ ist Tāʾ at-taʾnīth, kein Subjekt.","w":["Auch bei الْبِنْتُ fällt das Pronomen weg.","هِيَ gibt es im Nominalsatz.","Es geht um eine Person."]},
 {"q":"Welches Relativpronomen passt? الْبِنْتُ … جَلَسَتْ أَمَامِي أُخْتِي.","a":["الَّتِي","الَّذِي","هَذِهِ","مَنْ"],"e":"Weiblicher Bezug → الَّتِي.","w":["الَّذِي ist männlich.","هَذِهِ heißt „diese“.","مَنْ fragt „wer?“."]}
],
"m13": [
 {"q":"Warum sagt man مُسْلِمُونَ, aber كُتُبٌ?","a":["Personen bilden oft den gesunden Plural, كِتَابٌ hat einen gebrochenen Plural.","Weil كِتَابٌ weiblich ist.","Weil مُسْلِمُونَ bestimmt ist.","Beide sind gebrochene Plurale."],"e":"Den Plural immer mitlernen; -ūna gibt es nur bei männlichen Personen.","w":["كِتَابٌ ist männlich.","Beide sind unbestimmt.","مُسْلِمُونَ ist ein gesunder Plural."]},
 {"q":"Welches Wort passt? … الطُّلَّابُ مِنَ الْيَابَانِ.","a":["هَؤُلَاءِ","هَذَا","هَذِهِ","ذَلِكَ"],"e":"Plural von Personen, nah → هَؤُلَاءِ.","w":["هَذَا ist Singular.","هَذِهِ steht für Sachplurale, nicht für Personen.","ذَلِكَ ist Singular."]},
 {"q":"Wie heißt „ihr Buch“ (mehrere Frauen)?","a":["كِتَابُهُنَّ","كِتَابُهُمْ","كِتَابُهَا","كِتَابُكُنَّ"],"e":"ـهُنَّ = ihr (w. Pl.).","w":["ـهُمْ ist für Männer.","ـهَا ist für eine Frau.","ـكُنَّ heißt „euer“ (w.)."]},
 {"q":"Warum spricht man das Alif in ذَهَبُوا nicht?","a":["Es ist nur ein Schreibzeichen nach dem و der Mehrzahl.","Weil es ein Hamza ist.","Weil es der Plural ist.","Man spricht es doch."],"e":"ذَهَبُوا = dhahabū.","w":["Es ist ein einfaches Alif ohne Hamza.","Der Plural steckt im و, nicht im Alif.","Es wird nicht gesprochen."]}
],
"m14": [
 {"q":"Was ist der Unterschied zwischen ذَهَبْنَا und ذَهَبْنَ?","a":["ذَهَبْنَا (langes ā) = wir gingen, ذَهَبْنَ = sie (Frauen) gingen","Beide heißen „wir gingen“.","ذَهَبْنَا = sie gingen, ذَهَبْنَ = wir gingen","Nur die Schreibung ist anders."],"e":"Das Alif am Ende macht den Unterschied.","w":["ذَهَبْنَ ist die 3. Person weiblich Plural.","Es ist genau umgekehrt.","Auch die Bedeutung ist anders."]},
 {"q":"Warum hat نُوحٌ Tanwīn, إِبْرَاهِيمُ aber nicht?","a":["Kurze fremde Namen (3 Buchstaben, mittlerer ruhend) bekommen Tanwīn.","Weil نُوحٌ arabisch ist.","Weil إِبْرَاهِيمُ bestimmt ist.","Weil نُوحٌ im Genitiv steht."],"e":"Ausnahme bei fremden Namen: نُوحٌ، لُوطٌ.","w":["نُوحٌ ist ebenfalls ein fremder Name.","Beide sind Eigennamen ohne Artikel.","Die Regel gilt in jedem Fall."]},
 {"q":"Was heißt بَيْتُ الْإِمَامِ الْجَدِيدِ (mit -i am Ende)?","a":["das Haus des neuen Imams","das neue Haus des Imams","Das Haus des Imams ist neu.","ein neues Haus eines Imams"],"e":"الْجَدِيدِ im Genitiv beschreibt den Imam; mit -u (الْجَدِيدُ) beschriebe es das Haus.","w":["Dann müsste das Adjektiv -u haben wie بَيْتُ.","Ein Satz bräuchte ein unbestimmtes Prädikat.","Alles ist bestimmt."]},
 {"q":"In welchem Fall steht das Nomen nach أَيُّ?","a":["Genitiv (Muḍāf ilaihi)","Nominativ","Akkusativ","wie أَيُّ selbst"],"e":"أَيُّ بَيْتٍ، مِنْ أَيِّ بَلَدٍ – أَيّ ist Muḍāf.","w":["Das Nomen danach steht immer im Genitiv.","Kein Akkusativ; es ist Muḍāf ilaihi.","أَيّ wechselt den Fall, das Nomen danach nicht."]}
],
"m15": [
 {"q":"Warum steht nach قَبْلَ und بَعْدَ immer der Genitiv?","a":["Sie sind immer Muḍāf; das folgende Nomen ist Muḍāf ilaihi.","Weil sie Präpositionen sind.","Weil sie Zeit angeben.","Weil sie weiblich sind."],"e":"قَبْلَ الصَّلَاةِ, بَعْدَ الدَّرْسِ – Iḍāfa.","w":["Grammatisch sind sie Nomen (Ẓarf), keine Präpositionen – das Ergebnis ist aber auch Genitiv.","Die Zeitbedeutung bestimmt nicht den Fall.","Sie haben kein Geschlecht, das den Fall bestimmt."]},
 {"q":"Welches Pronomen passt zu بَيْتُكُنَّ?","a":["أَنْتُنَّ","أَنْتُمْ","هُنَّ","أَنْتِ"],"e":"ـكُنَّ gehört zu أَنْتُنَّ (ihr, Frauen).","w":["Zu أَنْتُمْ gehört ـكُمْ.","Zu هُنَّ gehört ـهُنَّ.","Zu أَنْتِ gehört ـكِ."]},
 {"q":"Ordne zu: ذَهَبْتُمْ","a":["ihr (Männer) gingt","wir gingen","sie (Männer) gingen","ihr (Frauen) gingt"],"e":"-tum = ihr (m.).","w":["„wir gingen“ ist ذَهَبْنَا.","„sie gingen“ ist ذَهَبُوا.","„ihr (w.)“ ist ذَهَبْتُنَّ."]},
 {"q":"Was bedeutet قَبْلَ in ذَهَبْتُ قَبْلَ الْأَذَانِ?","a":["vor (zeitlich)","vor (örtlich)","nach","während"],"e":"Zeitlich „vor“ ist قَبْلَ; örtlich „vor“ ist أَمَامَ.","w":["Örtlich „vor“ ist أَمَامَ.","„nach“ ist بَعْدَ.","„während“ ist أَثْنَاءَ."]}
],
"m16": [
 {"q":"Warum sagt man هَذِهِ كُتُبٌ und nicht هَؤُلَاءِ كُتُبٌ?","a":["Plurale von Sachen behandelt man wie weiblichen Singular.","Weil كُتُبٌ weiblich ist.","Weil هَؤُلَاءِ nur für Frauen steht.","Beides ist richtig."],"e":"هَؤُلَاءِ steht nur für Personen.","w":["كِتَابٌ ist männlich; nur der Sachplural wird weiblich behandelt.","هَؤُلَاءِ steht für Männer und Frauen.","Für Sachen ist هَؤُلَاءِ falsch."]},
 {"q":"Warum heißt es خَرَجَتِ الْكِلَابُ, aber خَرَجَ الطُّلَّابُ?","a":["Tiere sind nicht vernunftbegabt: ihr Plural gilt als weiblicher Singular.","Weil كَلْبٌ weiblich ist.","Weil الْكِلَابُ Objekt ist.","Das ist beliebig."],"e":"Bei Personen steht das Verb männlich, bei Sach- und Tierplural weiblich.","w":["كَلْبٌ ist männlich.","الْكِلَابُ ist Subjekt (-u).","Es gibt eine feste Regel."]},
 {"q":"Welches Adjektiv passt? هَؤُلَاءِ طُلَّابٌ …","a":["جُدُدٌ","جَدِيدَةٌ","جَدِيدٌ","جَدِيدَاتٌ"],"e":"Personen im Plural → Adjektiv im Plural.","w":["Weiblicher Singular gilt nur für Sachen.","Das Adjektiv muss im Plural stehen.","طُلَّابٌ sind männlich."]},
 {"q":"Warum hat مَسَاجِدُ kein Tanwīn?","a":["Das Pluralmuster mafāʿil ist Diptoton.","Weil es weiblich ist.","Weil es bestimmt ist.","Weil es ein Ortsname ist."],"e":"مَسَاجِدُ، دَفَاتِرُ – ohne Tanwīn.","w":["Das Geschlecht spielt keine Rolle.","Es ist unbestimmt; trotzdem ohne Tanwīn.","Es ist ein gewöhnliches Nomen im Plural."]}
],
"m17": [
 {"q":"Finde den Fehler: هَذِهِ قُمْصَانٌ رَخِيصُونَ","a":["Sachplural → Adjektiv im weiblichen Singular: رَخِيصَةٌ","هَذِهِ muss هَؤُلَاءِ heißen.","قُمْصَانٌ braucht الْ.","Kein Fehler."],"e":"قُمْصَانٌ sind Sachen.","w":["هَؤُلَاءِ steht nur für Personen.","„Das sind billige Hemden“ braucht ein unbestimmtes Prädikat.","Doch: -ūna gilt nur für Personen."]},
 {"q":"Welches Pronomen passt? أَيْنَ الْقُمْصَانُ؟ …","a":["هِيَ فِي الْحَقِيبَةِ","هُمْ فِي الْحَقِيبَةِ","هُوَ فِي الْحَقِيبَةِ","هُنَّ فِي الْحَقِيبَةِ"],"e":"Sachplural → هِيَ.","w":["هُمْ steht für Personen.","Sachplural gilt als weiblich.","هُنَّ steht für weibliche Personen."]},
 {"q":"Was lernt man aus حِمَارٌ → حُمُرٌ / حَمِيرٌ?","a":["Ein Wort kann mehrere gebrochene Plurale haben.","Der Plural wird immer mit حَ gebildet.","حُمُرٌ ist der Dual.","حَمِيرٌ ist weiblich."],"e":"Deshalb lernt man den Plural jedes Wortes mit.","w":["Es gibt über zwanzig Muster.","Der Dual wäre حِمَارَانِ.","Beide sind Plurale von حِمَارٌ."]}
],
"m18": [
 {"q":"Ab wie vielen steht im Arabischen der Plural?","a":["ab drei","ab zwei","ab vier","ab zehn"],"e":"Singular (1), Dual (2), Plural (3 und mehr).","w":["Für zwei gibt es den Dual.","Schon ab drei.","Schon ab drei."]},
 {"q":"Warum schreibt man كِتَابًا mit Alif, سَيَّارَةً aber ohne?","a":["Wörter auf ة bekommen beim Akkusativ-Tanwīn kein Alif.","Weil سَيَّارَةً im Genitiv steht.","Weil كِتَابًا bestimmt ist.","Beide werden mit Alif geschrieben."],"e":"Das Alif wird nicht gesprochen; ة trägt das Tanwīn selbst.","w":["Beide stehen im Akkusativ (-an).","Beide sind unbestimmt.","سَيَّارَةً hat kein Alif."]},
 {"q":"Warum steht nach كَمْ der Singular im Akkusativ?","a":["Das Wort nach كَمْ ist ein Tamyīz (Spezifizierung).","Weil es Objekt ist.","Weil كَمْ eine Präposition ist.","Weil es Plural ist."],"e":"كَمْ كِتَابًا؟ – „Wie viele (an) Büchern?“","w":["Es gibt kein Verb, das es als Objekt hat.","كَمْ ist ein Fragenomen.","Nach كَمْ steht der Singular."]},
 {"q":"Welche Form ist der Dual von هَذِهِ?","a":["هَاتَانِ","هَذَانِ","هَؤُلَاءِ","هُمَا"],"e":"هَذَا → هَذَانِ, هَذِهِ → هَاتَانِ.","w":["هَذَانِ ist männlich.","هَؤُلَاءِ ist Plural.","هُمَا ist ein Pronomen."]}
],
"m19": [
 {"q":"Warum heißt es ثَلَاثَةُ كُتُبٍ mit ة, obwohl كِتَابٌ männlich ist?","a":["Die Zahlen 3–10 haben das umgekehrte Geschlecht des Gezählten.","Weil كُتُبٌ weiblich ist.","Weil die Zahl im Nominativ steht.","Das ist ein Fehler."],"e":"Männliches Gezähltes → Zahl mit ة; weibliches → ohne ة.","w":["Es zählt das Geschlecht des Singulars كِتَابٌ.","Der Fall hat damit nichts zu tun.","Das ist die Regel."]},
 {"q":"Warum stehen وَاحِدٌ und اثْنَانِ nach dem Nomen?","a":["Sie sind Adjektive, keine Muḍāf wie 3–10.","Weil sie weiblich sind.","Weil sie Fragewörter sind.","Weil sie im Genitiv stehen."],"e":"كِتَابٌ وَاحِدٌ, كِتَابَانِ اثْنَانِ – betonend.","w":["وَاحِدٌ ist männlich.","Sie fragen nicht.","Sie folgen dem Fall ihres Nomens."]},
 {"q":"Warum heißt es رَأَيْتُ خَمْسَةَ رِجَالٍ (mit -a)?","a":["Die Zahl ist hier Objekt und steht im Akkusativ.","Weil رِجَالٌ Plural ist.","Weil fünf immer -a hat.","Weil ein Genitiv folgt."],"e":"Die Zahl bekommt den Fall ihrer Rolle im Satz.","w":["Der Fall der Zahl hängt nicht vom Gezählten ab.","Als Subjekt hätte sie -u.","Das Gezählte bestimmt nicht den Fall der Zahl."]},
 {"q":"In welcher Form steht das Gezählte nach 3–10?","a":["Plural im Genitiv","Singular im Akkusativ","Dual","Singular im Genitiv"],"e":"ثَلَاثَةُ كُتُبٍ – Muḍāf ilaihi.","w":["Das gilt nach كَمْ.","Nach 3–10 steht der Plural.","Der Singular steht erst nach 100 und 1000."]}
],
"m20": [
 {"q":"Warum heißt es ثَلَاثُ بَنَاتٍ ohne ة?","a":["بِنْتٌ ist weiblich; die Zahl hat dann das umgekehrte Geschlecht (ohne ة).","Weil بَنَاتٌ Plural ist.","Weil die Zahl im Genitiv steht.","Weil Töchter Personen sind."],"e":"Weibliches Gezähltes → Zahl ohne ة.","w":["Das Gezählte ist nach 3–10 immer Plural.","Die Zahl steht im Nominativ.","Personen oder Sachen – das Geschlecht zählt."]},
 {"q":"Was unterscheidet عَشَرَةُ von عَشْرُ?","a":["عَشَرَةُ (Fatḥa, ة) für männliches, عَشْرُ (Sukūn) für weibliches Gezähltes","Nichts.","عَشْرُ ist „zehnter“.","عَشَرَةُ ist Plural."],"e":"عَشَرَةُ رِجَالٍ – عَشْرُ نِسَاءٍ.","w":["Es gibt einen Unterschied in Vokal und Endung.","„zehnter“ ist عَاشِرٌ.","Beide sind die Zahl zehn."]},
 {"q":"Welche Form passt? لِي أُخْتٌ …","a":["وَاحِدَةٌ","وَاحِدٌ","أَحَدٌ","اثْنَتَانِ"],"e":"أُخْتٌ ist weiblich → وَاحِدَةٌ.","w":["وَاحِدٌ ist männlich.","أَحَدٌ heißt „irgendjemand“.","اثْنَتَانِ heißt „zwei“."]}
],
"m21": [
 {"q":"Welche zwei Wörter bedeuten dasselbe?","a":["ذَاكَ und ذَلِكَ","هَذَا und ذَلِكَ","تِلْكَ und هَذِهِ","هَذَا und هَذِهِ"],"e":"ذَاكَ = ذَلِكَ „jener“.","w":["هَذَا ist nah, ذَلِكَ fern.","تِلْكَ ist fern, هَذِهِ nah.","Sie unterscheiden sich im Geschlecht."]},
 {"q":"Welcher Satz ist richtig? („Hier sind drei große Häuser.“)","a":["هُنَا ثَلَاثَةُ بُيُوتٍ كَبِيرَةٍ.","هُنَا ثَلَاثُ بُيُوتٍ كَبِيرَةٍ.","هُنَا ثَلَاثَةُ بَيْتٍ كَبِيرٍ.","هُنَا ثَلَاثَةٌ بُيُوتٌ كَبِيرَةٌ."],"e":"بَيْتٌ männlich → ثَلَاثَةُ; Plural im Genitiv; Sachplural-Adjektiv weiblich Singular.","w":["بَيْتٌ ist männlich, also braucht die Zahl ein ة.","Nach 3–10 steht der Plural.","Die Zahl ist Muḍāf: kein Tanwīn, Gezähltes im Genitiv."]},
 {"q":"Was ist ـهُ in نُحِبُّهُ?","a":["das Objekt „ihn“","das Subjekt „er“","„sein“","ein Zeichen für Plural"],"e":"نُحِبُّ = wir lieben, ـهُ = ihn.","w":["Das Subjekt ist „wir“ (نُـ).","An einem Verb heißt ـهُ „ihn“, nicht „sein“.","Es zeigt keinen Plural."]}
],
"m22": [
 {"q":"Wann verliert ein normales Nomen sein Tanwīn? (drei Fälle)","a":["mit الْ, als Muḍāf, nach يَا","im Plural, im Dual, im Genitiv","nur im Akkusativ","nie"],"e":"الْكِتَابُ – كِتَابُ بِلَالٍ – يَا أُسْتَاذُ.","w":["Plural und Genitiv haben oft Tanwīn.","Im Akkusativ gibt es -an.","Es gibt drei Fälle."]},
 {"q":"Zu welcher Gruppe gehört حَمْزَةُ als Diptoton?","a":["männliche Namen auf ة","weibliche Namen","Farben","Plurale nach mafāʿil"],"e":"حَمْزَةُ، أُسَامَةُ, طَلْحَةُ – männliche Namen auf ة.","w":["حَمْزَةُ ist ein Mann.","Es ist keine Farbe.","Es ist kein Plural."]},
 {"q":"Warum hat أَحْمَرُ (rot) kein Tanwīn?","a":["Farbadjektive nach afʿal sind Diptota.","Weil es bestimmt ist.","Weil es weiblich ist.","Weil es ein Name ist."],"e":"أَحْمَرُ، أَسْوَدُ، أَبْيَضُ, أَخْضَرُ.","w":["Es hat keinen Artikel.","Die weibliche Form wäre حَمْرَاءُ.","Es ist ein Adjektiv."]},
 {"q":"Welches Wort ist KEIN Diptoton?","a":["مَسْجِدٌ","مَسَاجِدُ","أَصْدِقَاءُ","زَيْنَبُ"],"e":"Der Singular مَسْجِدٌ hat Tanwīn; nur sein Plural مَسَاجِدُ nicht.","w":["mafāʿil-Plurale sind Diptota.","afʿilāʾ-Plurale sind Diptota.","Weibliche Namen sind Diptota."]}
],
"m23": [
 {"q":"Wie erkennt man den Genitiv bei einem Diptoton ohne الْ?","a":["an der Fatḥa (statt Kasra)","an der Kasra","am Tanwīn","an der Ḍamma"],"e":"مِنْ أَحْمَدَ – Fatḥa vertritt die Kasra.","w":["Kasra bekommt ein Diptoton nur mit الْ oder als Muḍāf.","Diptota haben kein Tanwīn.","Ḍamma zeigt den Nominativ."]},
 {"q":"Warum heißt es فِي الْمَسَاجِدِ mit Kasra?","a":["Mit الْ bekommt auch ein Diptoton wieder die Kasra.","Weil فِي eine andere Präposition ist.","Weil مَسَاجِدُ kein Diptoton ist.","Das ist ein Fehler."],"e":"Ebenso als Muḍāf: فِي مَسَاجِدِ الْمَدِينَةِ.","w":["Das gilt für jede Präposition.","مَسَاجِدُ ist ein Diptoton.","Das ist die Regel."]},
 {"q":"Ist die Fatḥa in كِتَابُ أَحْمَدَ ein Akkusativ?","a":["Nein, sie ist das Genitivzeichen des Diptotons.","Ja, أَحْمَدَ ist Objekt.","Ja, weil كِتَابُ Nominativ ist.","Nein, es ist Nominativ."],"e":"أَحْمَدَ ist Muḍāf ilaihi; die Fatḥa steht für die Kasra.","w":["Es gibt kein Verb, also kein Objekt.","Der Fall von كِتَابُ bestimmt nicht den des Besitzers.","Der Muḍāf ilaihi steht im Genitiv."]},
 {"q":"Welche Form ist richtig? „mit Zainab“","a":["مَعَ زَيْنَبَ","مَعَ زَيْنَبِ","مَعَ زَيْنَبٍ","مَعَ زَيْنَبُ"],"e":"زَيْنَبُ ist Diptoton: Genitiv mit Fatḥa.","w":["Ohne الْ bekommt ein Diptoton im Genitiv Fatḥa.","Diptota haben kein Tanwīn.","Nach مَعَ steht der Genitiv."]}
],
"b2-01": [
 {"q":"Was ändert إِنَّ am Satz الْكِتَابُ سَهْلٌ?","a":["Das Subjekt wird manṣūb: إِنَّ الْكِتَابَ سَهْلٌ.","Das Prädikat wird manṣūb: إِنَّ الْكِتَابُ سَهْلًا.","Beide werden manṣūb.","Nichts, nur die Bedeutung."],"e":"إِنَّ setzt ihren Ism in den Akkusativ; das Khabar bleibt marfūʿ.","w":["Das ist die Wirkung von كَانَ, nicht von إِنَّ.","Das Khabar bleibt im Nominativ.","Auch die Endung des Subjekts ändert sich."]},
 {"q":"Was bedeutet إِنَّ im Satz?","a":["Nachdruck: „wahrlich, gewiss“","Verneinung: „nicht“","Frage: „ob“","Zeit: „als“"],"e":"إِنَّ bekräftigt die Aussage.","w":["Verneinen tut لَيْسَ oder مَا.","Fragen bildet man mit أَ oder هَلْ.","„als“ ist لَمَّا."]},
 {"q":"Warum sagt man إِنَّهُ مُدَرِّسٌ statt إِنَّ هُوَ مُدَرِّسٌ?","a":["Nach إِنَّ steht das Pronomen angehängt in der Akkusativform.","Weil هُوَ weiblich ist.","Weil مُدَرِّسٌ Objekt ist.","Beides ist üblich."],"e":"إِنَّكَ، إِنَّهُ، إِنَّهَا، إِنَّنِي/إِنِّي.","w":["هُوَ ist männlich.","مُدَرِّسٌ ist das Khabar.","Das selbstständige Pronomen steht nach إِنَّ nicht."]},
 {"q":"Wann sagt man أَمْ, wann أَوْ („oder“)?","a":["أَمْ in Entweder-oder-Fragen, أَوْ in Aussagen und Befehlen","أَمْ in Aussagen, أَوْ in Fragen","Beide sind gleich.","أَمْ nur bei Personen"],"e":"أَقَهْوَةً تُرِيدُ أَمْ شَايًا؟ – خُذْ هَذَا أَوْ ذَاكَ.","w":["Genau umgekehrt.","Das Buch unterscheidet sie.","أَمْ steht bei allem, das erfragt wird."]}
],
"b2-02": [
 {"q":"Warum steht in لَيْسَ الْبَيْتُ بِجَدِيدٍ das Khabar im Genitiv?","a":["Wegen des zusätzlichen بِـ davor","Weil لَيْسَ den Genitiv verlangt","Weil جَدِيدٌ ein Adjektiv ist","Weil الْبَيْتُ bestimmt ist"],"e":"Das بِـ ist ein Zusatz; ohne بِـ stünde das Khabar im Akkusativ.","w":["Ohne بِـ wäre es لَيْسَ الْبَيْتُ جَدِيدًا (Akkusativ).","Die Wortart bestimmt den Fall nicht.","Die Bestimmtheit des Subjekts ändert nichts."]},
 {"q":"Warum sagt man لَسْتُ und nicht لَيْسَ أَنَا?","a":["لَيْسَ wird wie ein Verb im Perfekt konjugiert.","Weil أَنَا weiblich ist.","Weil لَسْتُ eine Frage ist.","Beides ist gleich üblich."],"e":"لَسْتُ، لَسْتَ، لَسْتِ، لَسْنَا، لَيْسُوا …","w":["أَنَا gilt für beide Geschlechter.","لَسْتُ ist eine Aussage.","Man hängt die Endung an: لَسْتُ."]},
 {"q":"Welche Form passt? „Die Schülerinnen sind nicht faul.“","a":["لَيْسَتِ الطَّالِبَاتُ بِكَسْلَانَاتٍ","لَيْسَ الطَّالِبَاتُ بِكَسْلَانَاتٍ","لَسْتُ الطَّالِبَاتُ بِكَسْلَانَاتٍ","لَيْسَتِ الطَّالِبَاتِ بِكَسْلَانَاتٍ"],"e":"Weibliches Subjekt → لَيْسَتْ; vor الْ wird das Sukūn zu Kasra.","w":["Bei weiblichem Subjekt steht لَيْسَتْ.","لَسْتُ heißt „ich bin nicht“.","Das Subjekt von لَيْسَ bleibt im Nominativ."]},
 {"q":"Warum schreibt man بِلَالُ بْنُ حَامِدٍ ohne Alif bei ابْن?","a":["Zwischen zwei Namen in „X, Sohn des Y“ fällt das Alif weg.","Weil ابْن im Genitiv steht.","Weil بِلَال weiblich ist.","Das ist ein Druckfehler."],"e":"Außerdem verliert der erste Name sein Tanwīn.","w":["ابْن steht hier im Nominativ.","بِلَال ist männlich.","Das ist eine feste Regel."]}
],
"b2-03": [
 {"q":"Warum bleibt أَطْوَلُ in آمِنَةُ أَطْوَلُ مِنْ بِلَالٍ männlich?","a":["Der Komparativ mit مِنْ bleibt immer unverändert.","Weil بِلَالٌ männlich ist.","Weil آمِنَةُ ein Name ist.","Das ist ein Fehler."],"e":"أَفْعَلُ + مِنْ gilt für m., f., Singular und Plural.","w":["Es richtet sich nicht nach dem Vergleichswort.","Auch bei الْبَنَاتُ bleibt es أَطْوَلُ.","Das ist die Regel."]},
 {"q":"Was ist der Unterschied zwischen أَكْبَرُ مِنْ بَيْتٍ und أَكْبَرُ بَيْتٍ?","a":["„größer als ein Haus“ – „das größte Haus“","Beide heißen „größer als ein Haus“.","„das größte Haus“ – „größer als ein Haus“","Beide heißen „ein großes Haus“."],"e":"Mit مِنْ: Komparativ; mit Genitiv danach: Superlativ.","w":["Ohne مِنْ ist es Superlativ.","Genau umgekehrt.","„ein großes Haus“ wäre بَيْتٌ كَبِيرٌ."]},
 {"q":"Welches Wort setzt wie إِنَّ sein Nomen in den Akkusativ?","a":["لَكِنَّ","لَكِنْ","لَيْسَ","كَانَ"],"e":"Die Schwestern von إِنَّ: أَنَّ، لَكِنَّ، كَأَنَّ، لَعَلَّ.","w":["لَكِنْ ohne Shadda wirkt nicht.","Nach لَيْسَ bleibt das Subjekt im Nominativ.","Nach كَانَ bleibt das Subjekt im Nominativ."]},
 {"q":"Wann antwortet man mit بَلَى?","a":["wenn man einer verneinten Frage widerspricht","auf jede Ja/Nein-Frage","wenn man ablehnt","wenn man nicht weiß"],"e":"أَلَسْتَ طَالِبًا؟ – بَلَى، أَنَا طَالِبٌ.","w":["Auf normale Fragen antwortet man mit نَعَمْ.","Ablehnen ist لَا.","„Ich weiß nicht“ ist لَا أَدْرِي."]}
],
"b2-04": [
 {"q":"Wie viele Radikale haben die meisten arabischen Verben?","a":["drei","zwei","vier","fünf"],"e":"ذَهَبَ: ذ-ه-ب.","w":["Zwei Radikale gibt es nicht als Grundform.","Vierradikalige Verben sind selten.","Fünf Radikale gibt es bei Verben nicht."]},
 {"q":"Was ist der Unterschied zwischen dem تْ in ذَهَبَتْ und dem تُ in ذَهَبْتُ?","a":["تْ zeigt nur weiblich an, تُ ist das Subjekt „ich“.","Beide sind das Subjekt.","Beide zeigen weiblich an.","تْ ist „ich“, تُ ist „sie“."],"e":"Das تُ hat einen Vokal und ist ein Pronomen.","w":["Das تْ (Sukūn) ist kein Pronomen.","„ich“ ist nicht weiblich-spezifisch.","Genau umgekehrt."]},
 {"q":"Was heißt isnād (الْإِسْنَادُ)?","a":["das Anhängen der Personalendungen an das Verb","die Satzanalyse","die Verneinung","die Genitivverbindung"],"e":"ذَهَبْتُ، ذَهَبْنَا، ذَهَبُوا …","w":["Die Satzanalyse heißt Iʿrāb.","Verneinung heißt nafy.","Die Genitivverbindung heißt Iḍāfa."]},
 {"q":"Welche Form ist das Perfekt mit „wir“?","a":["ذَهَبْنَا","ذَهَبْنَ","نَذْهَبُ","ذَهَبُوا"],"e":"-nā = wir.","w":["ذَهَبْنَ ist „sie (Frauen)“.","نَذْهَبُ ist Präsens.","ذَهَبُوا ist „sie (Männer)“."]}
],
"b2-05": [
 {"q":"Warum ist ذَهَبُوا الطُّلَّابُ falsch?","a":["Das Verb hätte zwei Fāʿil (و und الطُّلَّابُ).","Weil الطُّلَّابُ im Akkusativ stehen muss.","Weil ذَهَبَ weiblich sein muss.","Es ist nicht falsch."],"e":"Vor einem genannten Fāʿil steht das Verb im Singular: ذَهَبَ الطُّلَّابُ.","w":["Der Fāʿil steht im Nominativ.","الطُّلَّابُ sind Männer.","Doch: zwei Subjekte sind nicht möglich."]},
 {"q":"Was ist in الطُّلَّابُ ذَهَبُوا das و?","a":["der Fāʿil; الطُّلَّابُ ist Mubtadaʾ","ein „und“","das Objekt","Zeichen des Duals"],"e":"Nominalsatz: Mubtadaʾ + Khabar (Verbalsatz mit eigenem Fāʿil).","w":["و am Verb ist hier ein Pronomen.","Es gibt kein Objekt.","Der Dual hätte ا."]},
 {"q":"Warum steht شَرِبَ حَامِدٌ الْمَاءَ mit -a auf الْمَاءَ?","a":["الْمَاءَ ist das Objekt (manṣūb).","Weil الْمَاءُ weiblich ist.","Weil ein Eigenname davorsteht.","Weil es Plural ist."],"e":"Mafʿūl bihi steht im Akkusativ.","w":["الْمَاءُ ist männlich; der Fall kommt von der Rolle.","Der Name ist der Fāʿil.","الْمَاءُ ist Singular."]},
 {"q":"Woran erkennt man in فَتَحَ الْوَلَدُ الْبَابَ, wer was tut?","a":["an den Endungen: -u = Subjekt, -a = Objekt","an der Wortstellung allein","am Artikel","gar nicht"],"e":"Die Fallendungen zeigen die Rolle, auch bei anderer Wortstellung.","w":["Die Stellung hilft, aber die Endung entscheidet.","Beide haben den Artikel.","Doch: an den Endungen."]}
],
"b2-06": [
 {"q":"Welche vier Bedeutungen kann ذهبت ohne Vokale haben?","a":["sie ging, du (m.) gingst, du (f.) gingst, ich ging","er ging, sie ging, wir gingen, ihr gingt","nur „ich ging“","sie gingen, ihr gingt, wir gingen, ich ging"],"e":"ذَهَبَتْ، ذَهَبْتَ، ذَهَبْتِ، ذَهَبْتُ.","w":["„er ging“ ist ذَهَبَ, „wir“ ذَهَبْنَا.","Ohne Vokale sind vier Lesungen möglich.","„sie gingen“ ist ذَهَبُوا."]},
 {"q":"Welche Regel gilt bei 13–19 mit weiblichem Gezählten?","a":["Der Zehner stimmt überein (عَشْرَةَ), der Einer hat das Gegenteil (ohne ة).","Beide Teile stimmen überein.","Beide Teile haben das Gegenteil.","Es gibt keine Regel."],"e":"ثَلَاثَ عَشْرَةَ طَالِبَةً.","w":["Das gilt nur für 11 und 12.","Der Zehner stimmt überein.","Doch: umgekehrtes Geschlecht beim Einer."]},
 {"q":"Warum heißt es بِأَيِّ قَلَمٍ mit Kasra auf أَيِّ?","a":["أَيُّ steht nach der Präposition بِـ im Genitiv.","Weil قَلَمٌ im Genitiv steht.","Weil أَيُّ immer Kasra hat.","Weil es eine Frage ist."],"e":"أَيُّ bekommt den Fall seiner Stellung: nach بِـ Genitiv.","w":["قَلَمٍ ist Muḍāf ilaihi; das bestimmt nicht den Fall von أَيِّ.","Als Subjekt hat es -u, als Objekt -a.","Die Frage bestimmt keinen Fall."]},
 {"q":"Warum sagt man أَظُنُّ أَنَّ … und nicht أَظُنُّ إِنَّ …?","a":["Nach Verben wie „glauben, hören“ steht أَنَّ, nur nach قَالَ steht إِنَّ.","Weil أَظُنُّ weiblich ist.","Weil أَنَّ „nicht“ heißt.","Beides ist gleich."],"e":"قَالَ: إِنَّ … – aber سَمِعْتُ / أَظُنُّ أَنَّ …","w":["أَظُنُّ ist „ich glaube“.","أَنَّ heißt „dass“.","Die Wahl hängt vom Verb ab."]}
],
"b2-07": [
 {"q":"Warum heißt es فِي بَيْتِهِ, aber بَيْتُهُ?","a":["Nach einem i wird ـهُ zu ـهِ (Vokalharmonie).","Weil فِي weiblich ist.","Weil ـهِ „ihr“ bedeutet.","Das ist beliebig."],"e":"Ebenso فِيهِ، بِهِ، عَلَيْهِ.","w":["Das Geschlecht spielt keine Rolle.","Auch ـهِ bedeutet „sein“.","Es ist eine feste Lautregel."]},
 {"q":"Warum wird مَرِيضٌ nach كَانَ zu مَرِيضًا?","a":["كَانَ setzt das Khabar in den Akkusativ.","كَانَ setzt das Subjekt in den Akkusativ.","Weil كَانَ ein Objekt hat.","Weil es Vergangenheit ist."],"e":"كَانَ بِلَالٌ مَرِيضًا – Ism marfūʿ, Khabar manṣūb.","w":["Das Subjekt bleibt im Nominativ.","كَانَ hat kein Objekt, sondern ein Khabar.","Die Zeit erklärt nicht den Fall."]},
 {"q":"Was unterscheidet كَانَ von إِنَّ in der Wirkung?","a":["كَانَ: Khabar manṣūb; إِنَّ: Ism manṣūb","Beide machen das Subjekt manṣūb.","Beide machen das Khabar manṣūb.","Keine Wirkung auf die Endungen."],"e":"كَانَ الْجَوُّ جَمِيلًا – إِنَّ الْجَوَّ جَمِيلٌ.","w":["Nach كَانَ bleibt das Subjekt marfūʿ.","Nach إِنَّ bleibt das Khabar marfūʿ.","Beide ändern Endungen."]},
 {"q":"Warum sagt man الرَّجُلُ ذُو اللِّحْيَةِ und nicht الرَّجُلُ الذُّو لِحْيَةٍ?","a":["ذُو kann keinen Artikel haben; die Bestimmtheit zeigt das Wort danach.","Weil ذُو weiblich ist.","Weil اللِّحْيَةِ Subjekt ist.","Beides ist richtig."],"e":"ذُو ist immer Muḍāf und wird durch den Muḍāf ilaihi bestimmt.","w":["ذُو ist männlich (weiblich: ذَاتُ).","اللِّحْيَةِ ist Muḍāf ilaihi.","الذُّو gibt es nicht."]}
],
"b2-08": [
 {"q":"Welches Subjekt hat ذَهَبَ, wenn kein Nomen folgt?","a":["ein unsichtbares Pronomen (هُوَ)","das Fatḥa am Ende","das ذ","keins"],"e":"ضَمِيرٌ مُسْتَتِرٌ تَقْدِيرُهُ هُوَ.","w":["Das Fatḥa ist nur die Endung.","ذ ist ein Radikal.","Jedes Verb hat einen Fāʿil."]},
 {"q":"Warum hat der dritte Radikal in ذَهَبْتُ ein Sukūn?","a":["Vor Endungen, die mit Konsonant beginnen, steht Sukūn.","Weil ذَهَبْتُ Futur ist.","Weil ich weiblich bin.","Das ist ein Fehler."],"e":"ذَهَبْتُ، ذَهَبْنَا، ذَهَبْنَ – immer Sukūn davor.","w":["ذَهَبْتُ ist Perfekt.","ذَهَبْتُ gilt für Männer und Frauen.","Das ist die Regel."]},
 {"q":"Welche Endungen zeigen die 2. Person im Perfekt?","a":["ـتَ، ـتِ، ـتُمْ، ـتُنَّ","ـتُ، ـنَا","ـوا، ـنَ","ـَ، ـَتْ"],"e":"du (m.), du (f.), ihr (m.), ihr (f.).","w":["Das ist die 1. Person.","Das ist die 3. Person Plural.","Das ist die 3. Person Singular."]}
],
"b2-09": [
 {"q":"Warum hat السَّمَاوَاتِ im Akkusativ -i statt -a?","a":["Der gesunde feminine Plural hat im Akkusativ -i.","Weil es im Genitiv steht.","Weil es bestimmt ist.","Das ist ein Fehler."],"e":"Akkusativ und Genitiv sind beim femininen Plural gleich: -āti.","w":["Es ist Objekt von خَلَقَ, also Akkusativ.","Der Artikel ändert den Fall nicht.","Das ist die Regel."]},
 {"q":"Wozu dient das n in سَأَلَنِي?","a":["Es schützt den letzten Vokal des Verbs (nūn al-wiqāya).","Es ist das Subjekt.","Es zeigt den Plural.","Es ist „uns“."],"e":"سَأَلَ + نِ + ي „mich“.","w":["Das Subjekt ist der Lehrer.","Es zeigt keinen Plural.","„uns“ wäre سَأَلَنَا."]},
 {"q":"Wie bildet man den Ausruf „Wie schön ist …!“?","a":["مَا أَجْمَلَ + Nomen im Akkusativ","مَا جَمِيلٌ + Nomen im Nominativ","كَمْ أَجْمَلُ + Nomen","أَجْمَلُ مِنْ + Nomen"],"e":"مَا أَجْمَلَ السَّمَاءَ!","w":["Staunen braucht die Form أَفْعَلَ.","Staunen drückt man mit مَا aus, nicht mit كَمْ.","Das ist ein Vergleich „schöner als“."]},
 {"q":"Warum heißt es يَا عَبْدَ اللَّهِ mit Fatḥa?","a":["Ein Munādā, der Muḍāf ist, steht im Akkusativ.","Weil اللَّه im Genitiv steht.","Weil يَا immer Fatḥa verlangt.","Weil es ein Name ist."],"e":"Aber يَا بِلَالُ (kein Muḍāf) – mit Ḍamma.","w":["Der Genitiv von اللَّه bestimmt nicht عَبْدَ.","Bei يَا بِلَالُ steht Ḍamma.","Auch Namen stehen nach يَا mit Ḍamma, wenn sie kein Muḍāf sind."]}
],
"b2-10": [
 {"q":"Welche drei Formen hat das arabische Verb?","a":["Perfekt, Präsens/Futur (Muḍāriʿ), Befehl","Vergangenheit, Gegenwart, Zukunft getrennt","nur Perfekt und Präsens","Singular, Dual, Plural"],"e":"الْمَاضِي، الْمُضَارِعُ، الْأَمْرُ.","w":["Gegenwart und Zukunft teilen eine Form.","Der Befehl ist die dritte Form.","Das sind Numeri, keine Verbformen."]},
 {"q":"Woran erkennt man die Verbgruppe (z. B. a–u)?","a":["am Vokal des zweiten Radikals in Perfekt und Präsens","am ersten Radikal","an der Vorsilbe","am Tanwīn"],"e":"كَتَبَ يَكْتُبُ: a im Perfekt, u im Präsens.","w":["Der erste Radikal hat im Präsens immer Sukūn.","Die Vorsilbe zeigt die Person.","Verben haben kein Tanwīn."]},
 {"q":"Warum steht nach عِشْرُونَ der Singular im Akkusativ (عِشْرُونَ طَالِبًا)?","a":["Nach 11–99 steht ein Tamyīz: Singular, manṣūb.","Weil عِشْرُونَ Plural ist.","Weil طَالِبٌ Objekt ist.","Das ist ein Fehler."],"e":"Nach 3–10: Plural im Genitiv; nach 11–99: Singular im Akkusativ.","w":["Die Form der Zahl bestimmt nicht die des Gezählten.","Es gibt kein Verb.","Das ist die Regel."]},
 {"q":"Welche Form hat der Einer bei 21–29?","a":["Er steht vor dem Zehner, mit وَ verbunden: ثَلَاثَةٌ وَعِشْرُونَ","Er steht hinter dem Zehner: عِشْرُونَ وَثَلَاثَةٌ","Er wird angehängt: عِشْرُونَثَلَاثَةٌ","Man nennt nur den Zehner."],"e":"Einer + وَ + Zehner.","w":["Im Arabischen kommt der Einer zuerst.","Die Teile werden mit وَ getrennt geschrieben.","Der Einer muss genannt werden."]}
],
"b2-11": [
 {"q":"Warum heißt es مَتَى تَذْهَبُ؟ ohne سَـ, obwohl es um die Zukunft geht?","a":["سَـ wird in Fragen nicht verwendet.","Weil تَذْهَبُ weiblich ist.","Weil مَتَى „wann“ Perfekt verlangt.","Das ist ein Fehler."],"e":"Der Muḍāriʿ umfasst ohnehin die Zukunft.","w":["تَذْهَبُ kann auch „du gehst“ heißen.","Das Verb steht im Präsens.","Das ist die Regel."]},
 {"q":"Was ist ein Maṣdar?","a":["ein Verbalnomen („das Schreiben“)","eine Befehlsform","ein Partizip („schreibend“)","eine Präposition"],"e":"جُلُوسٌ (das Sitzen), دُخُولٌ (das Eintreten).","w":["Der Befehl ist ein Verb.","Das Partizip ist z. B. جَالِسٌ.","Präpositionen sind فِي، عَلَى …"]},
 {"q":"Warum steht nach أَمَّا … ein فَـ?","a":["أَمَّا verlangt, dass die Aussage mit فَـ beginnt.","Weil فَـ „und“ heißt.","Weil ein Befehl folgt.","Das ist beliebig."],"e":"أَمَّا بِلَالٌ فَهُوَ مِنْ بَاكِسْتَانَ.","w":["فَـ ist hier kein bloßes „und“.","Es folgt eine Aussage.","Das ist eine feste Regel."]},
 {"q":"Wie verneint man Perfekt und Präsens?","a":["Perfekt mit مَا, Präsens mit لَا","beide mit لَيْسَ","Perfekt mit لَا, Präsens mit مَا","beide mit لَنْ"],"e":"مَا أَكَلْتُ – لَا أَفْهَمُ.","w":["لَيْسَ verneint Nominalsätze.","Genau umgekehrt (im Grundfall).","لَنْ verneint nur die Zukunft."]}
],
"b2-12": [
 {"q":"Was ist in تَذْهَبِينَ das ي?","a":["der Fāʿil („du“, weiblich)","das Zeichen des Indikativs","ein Objekt","ein Genitiv-ي"],"e":"ي = Fāʿil, ن = Indikativzeichen.","w":["Das Indikativzeichen ist das ن.","Es ist das Subjekt.","Verben haben keinen Genitiv."]},
 {"q":"Warum steht يَوْمَ in رَجَعْتُ يَوْمَ الْجُمُعَةِ im Akkusativ?","a":["Es ist Mafʿūl fīhi (Zeitangabe).","Es ist Objekt von رَجَعَ.","Weil الْجُمُعَةِ im Genitiv steht.","Weil es ein Wochentag ist."],"e":"Zeitangaben stehen im Akkusativ.","w":["رَجَعَ hat kein Objekt.","Der Genitiv danach kommt von der Iḍāfa.","Nicht der Tag, sondern die Funktion zählt."]},
 {"q":"Welche Form heißt „ihr (Frauen) versteht“?","a":["تَفْهَمْنَ","يَفْهَمْنَ","تَفْهَمِينَ","تَفْهَمُونَ"],"e":"تَـ + ـنَ = ihr (w.).","w":["يَفْهَمْنَ = sie (Frauen).","تَفْهَمِينَ = du (w.).","تَفْهَمُونَ = ihr (m.)."]}
],
"b2-13": [
 {"q":"Zerlege يَذْهَبُونَ richtig:","a":["يَـ (Präsens) + ذهب + و (Fāʿil) + ن (Indikativ)","يَـ (Fāʿil) + ذهب + ون (Plural)","يَذْهَبُ + ونَ (Objekt)","ي (er) + ذهب + ونَ (Zukunft)"],"e":"Die Vorsilbe zeigt das Präsens, و ist das Subjekt, ن das Indikativzeichen.","w":["Die Vorsilbe ist nicht der Fāʿil.","ونَ ist kein Objekt.","ونَ zeigt keine Zukunft."]},
 {"q":"Warum ist يَذْهَبْنَ in allen drei Modi gleich?","a":["Mit dem nūn der Frauen ist der Muḍāriʿ mabnī.","Weil es Plural ist.","Weil es Perfekt ist.","Weil es weiblich ist und keinen Fall hat."],"e":"Das nūn ist Fāʿil, nicht Endung.","w":["يَذْهَبُونَ ist auch Plural, ändert sich aber.","يَذْهَبْنَ ist Präsens.","Das Weibliche allein macht es nicht; das nūn der Frauen macht es."]},
 {"q":"Was ist das Indikativzeichen in يَذْهَبُ?","a":["die Ḍamma am Ende","das يَـ","das Sukūn auf ذ","es gibt keins"],"e":"Einfache Formen zeigen den Indikativ mit Ḍamma.","w":["يَـ zeigt Person und Präsens.","Das Sukūn gehört zum Muster.","Doch: die Ḍamma."]}
],
"b2-14": [
 {"q":"Wie bildet man den Befehl aus تَكْتُبُ?","a":["ta- vorne und -u hinten weglassen, Hilfs-Alif davor: اُكْتُبْ","nur das -u weglassen: تَكْتُبْ","ein Alif anhängen: تَكْتُبَا","das Perfekt nehmen: كَتَبَ"],"e":"تَكْتُبُ → كْتُبْ → اُكْتُبْ.","w":["تَكْتُبْ ist Jussiv (z. B. nach لَا), kein Befehl.","تَكْتُبَا ist Dual.","كَتَبَ heißt „er schrieb“."]},
 {"q":"Warum beginnt اُكْتُبْ mit u, aber اِجْلِسْ mit i?","a":["Das Hilfs-Alif hat u, wenn der zweite Radikal u hat, sonst i.","Weil كَتَبَ weiblich ist.","Weil جَلَسَ ein Objekt hat.","Das ist beliebig."],"e":"يَكْتُبُ (u) → اُكْتُبْ; يَجْلِسُ (i) → اِجْلِسْ; يَفْتَحُ (a) → اِفْتَحْ.","w":["Das Geschlecht hat damit nichts zu tun.","Ein Objekt ändert den Befehl nicht.","Es gibt eine feste Regel."]},
 {"q":"Warum spricht man in يَا بِلَالُ اكْتُبْ das u von اُكْتُبْ nicht?","a":["Das Hilfs-Alif (Hamzat al-waṣl) fällt nach einem Wort weg.","Weil بِلَالُ auf u endet.","Weil es eine Frage ist.","Man spricht es doch."],"e":"yā Bilālu ktub.","w":["Das hat nichts mit der Endung von بِلَالُ zu tun.","Es ist ein Befehl.","Nach einem Wort fällt es weg."]},
 {"q":"Welche Form ist der Befehl an mehrere Männer?","a":["اُكْتُبُوا","اُكْتُبْنَ","اُكْتُبِي","تَكْتُبُونَ"],"e":"Aus تَكْتُبُونَ: ta- und nūn weg.","w":["اُكْتُبْنَ sagt man zu Frauen.","اُكْتُبِي sagt man zu einer Frau.","تَكْتُبُونَ ist eine Aussage."]}
],
"b2-15": [
 {"q":"Was ist der Unterschied zwischen لَا تَذْهَبُ und لَا تَذْهَبْ?","a":["„du gehst nicht“ (Aussage) – „geh nicht!“ (Verbot)","Beide sind Verbote.","Beide sind Aussagen.","„geh nicht!“ – „du gehst nicht“"],"e":"Das verbietende لَا setzt den Jussiv (Sukūn).","w":["Mit Ḍamma ist es eine Aussage.","Mit Sukūn ist es ein Verbot.","Genau umgekehrt."]},
 {"q":"Warum fällt in لَا تَذْهَبُوا das nūn weg?","a":["Nach dem verbietenden لَا steht der Jussiv; bei den fünf Verben fällt das nūn weg.","Weil es Plural ist.","Weil es Perfekt ist.","Das ist ein Fehler."],"e":"تَذْهَبُونَ → لَا تَذْهَبُوا.","w":["Der Plural allein entfernt das nūn nicht (تَذْهَبُونَ).","Es ist Präsens.","Das ist die Regel."]},
 {"q":"Was bedeutet كَادَ?","a":["beinahe, fast","sofort","niemals","vielleicht"],"e":"كَادَ الْوَلَدُ يَبْكِي – „Der Junge weinte beinahe.“","w":["„sofort“ ist فَوْرًا.","„niemals“ ist أَبَدًا.","„vielleicht“ ist لَعَلَّ / رُبَّمَا."]},
 {"q":"Wie heißt das verbietende لَا auf Arabisch?","a":["لَا النَّاهِيَةُ","لَا النَّافِيَةُ","لَا النَّافِيَةُ لِلْجِنْسِ","لَا الْعَاطِفَةُ"],"e":"النَّهْيُ = Verbot.","w":["Das verneinende لَا (Aussage).","Das لَا, das eine ganze Gattung verneint.","Das verbindende لَا."]}
],
"b2-16": [
 {"q":"Warum hat die Vorsilbe in يُرِيدُ eine Ḍamma?","a":["Weil das Perfekt (أَرَادَ) vier Buchstaben hat.","Weil es eine Frage ist.","Weil es Futur ist.","Weil es weiblich ist."],"e":"Bei Verben mit vierbuchstabigem Perfekt haben die Vorsilben u.","w":["Auch in Aussagen: أُرِيدُ.","Die Vorsilbe gilt für jedes Präsens.","Das Geschlecht spielt keine Rolle."]},
 {"q":"Welche drei Arten von مَا kennt das Buch bis hier?","a":["Frage-mā, verneinendes mā, relatives mā","nur Frage-mā","Frage-mā und mā des Futurs","mā des Befehls und mā der Frage"],"e":"مَا اسْمُكَ؟ – مَا فَهِمْتُ – نَسِيتُ مَا قُلْتَ.","w":["Es gibt mehrere Arten.","مَا macht kein Futur.","مَا macht keinen Befehl."]},
 {"q":"Was ist ein Badal?","a":["eine Apposition: ein Wort, das das vorige ersetzt/erläutert, im selben Fall","ein Adjektiv","ein zweites Objekt","ein Ausruf"],"e":"أَخُوكَ الْحُسَيْنُ – الْحُسَيْنُ ist Badal.","w":["Ein Adjektiv (Naʿt) beschreibt eine Eigenschaft.","Ein Badal ist kein Objekt.","Ein Ausruf ist etwas anderes."]},
 {"q":"Welche Form passt zu سَيَّارَةٌ? „ein anderes Auto“","a":["سَيَّارَةٌ أُخْرَى","سَيَّارَةٌ آخَرُ","سَيَّارَةٌ أُخَرُ","سَيَّارَةٌ آخِرَةٌ"],"e":"آخَرُ (m.) – أُخْرَى (f.) – أُخَرُ (Pl.).","w":["آخَرُ ist männlich.","أُخَرُ ist Plural.","آخِرَةٌ heißt „letzte“ bzw. „Jenseits“."]}
],
"b2-17": [
 {"q":"Warum heißt es أُرِيدُ أَنْ أَذْهَبَ mit -a am Ende?","a":["Nach أَنْ steht der Muḍāriʿ im Subjunktiv.","Weil أَذْهَبَ Objekt ist.","Weil es Perfekt ist.","Weil أُرِيدُ weiblich ist."],"e":"أَنْ + Präsens → manṣūb.","w":["Ein Verb kann kein Objekt im Akkusativ sein.","Es ist Präsens.","Das Geschlecht bestimmt es nicht."]},
 {"q":"Was bedeutet لِـ in أَدْرُسُ لِأَفْهَمَ?","a":["„um zu“ (Zweck)","„für“ (Besitz)","„nicht“","„wahrlich“"],"e":"lām at-taʿlīl mit verstecktem أَنْ.","w":["Besitz-لِـ steht vor Nomen.","„nicht“ ist لَا.","„wahrlich“ ist إِنَّ / لَـ."]},
 {"q":"Welches Subjekt hat يُمْكِنُ in يُمْكِنُكَ أَنْ تَجْلِسَ?","a":["den Ausdruck أَنْ تَجْلِسَ („dein Sitzen“)","ـكَ","تَجْلِسَ allein","keins"],"e":"„Es ist dir möglich, dich zu setzen.“","w":["ـكَ ist das Objekt („dir“).","Der ganze Ausdruck mit أَنْ ist das Subjekt.","Jedes Verb hat ein Subjekt."]},
 {"q":"Warum sagt man خَرَجَتِ الْبَقَرَةُ, aber خَرَجَتِ السَّيَّارَةُ ODER خَرَجَ السَّيَّارَةُ?","a":["Bei weiblichen Lebewesen muss das Verb weiblich sein, bei grammatisch weiblichen Sachen ist beides erlaubt.","Weil السَّيَّارَةُ Plural ist.","Weil الْبَقَرَةُ bestimmt ist.","Beides ist immer beliebig."],"e":"Echtes Femininum → Pflicht; grammatisches → frei.","w":["السَّيَّارَةُ ist Singular.","Beide sind bestimmt.","Bei Lebewesen ist es Pflicht."]}
],
"b2-18": [
 {"q":"Welche Formen ändern sich im Subjunktiv von -u zu -a?","a":["يَذْهَبُ، تَذْهَبُ، أَذْهَبُ، نَذْهَبُ","يَذْهَبُونَ، تَذْهَبُونَ","يَذْهَبْنَ، تَذْهَبْنَ","تَذْهَبِينَ"],"e":"Die einfachen Formen wechseln den Vokal.","w":["Bei diesen fällt das nūn weg.","Diese bleiben unverändert.","Hier fällt das nūn weg."]},
 {"q":"Warum sagt man هُوَ كَمِثْلِي und nicht هُوَ كِي?","a":["كَـ steht nicht vor Pronomen; man schiebt مِثْل ein.","Weil ي weiblich ist.","Weil كَـ Genitiv verlangt.","Beides ist üblich."],"e":"Aber vor Nomen: كَالْمَسْجِدِ.","w":["ي heißt „mich/mein“ für beide Geschlechter.","Den Genitiv gibt es trotzdem nach كَـ.","كِي ist falsch."]},
 {"q":"Wann steht يَا أَيُّهَا statt nur يَا?","a":["vor einem Nomen mit Artikel: يَا أَيُّهَا النَّاسُ","vor Eigennamen","vor jedem Nomen","nur im Plural"],"e":"يَا بِلَالُ, aber يَا أَيُّهَا الرَّجُلُ.","w":["Vor Namen steht nur يَا.","Nur vor Nomen mit الْ.","Auch im Singular: يَا أَيُّهَا الرَّجُلُ."]},
 {"q":"Warum heißt es قَرَأْتُ الْكِتَابَ كُلَّهُ mit -a?","a":["كُلّ bekräftigt das Objekt und steht im selben Fall.","Weil كُلّ immer -a hat.","Weil ـهُ ein Objekt ist.","Weil es Plural ist."],"e":"حَضَرَ الطُّلَّابُ كُلُّهُمْ – dort mit -u.","w":["Beim Subjekt hat es -u.","ـهُ ist Muḍāf ilaihi an كُلّ.","الْكِتَابَ ist Singular."]}
],
"b2-19": [
 {"q":"Warum fällt in لَنْ أَذْهَبَ das سَـ weg?","a":["لَنْ trägt schon die Zukunft; سَـ und لَنْ stehen nicht zusammen.","Weil لَنْ Perfekt macht.","Weil أَذْهَبَ weiblich ist.","Das ist ein Fehler."],"e":"سَأَذْهَبُ → لَنْ أَذْهَبَ.","w":["لَنْ bezieht sich auf die Zukunft.","Das Geschlecht spielt keine Rolle.","Das ist die Regel."]},
 {"q":"Ordne zu: Welche Verneinung für welche Zeit?","a":["مَا + Perfekt, لَا + Präsens, لَنْ + Präsens (Futur)","لَنْ + Perfekt","لَا + Perfekt","مَا + Futur"],"e":"مَا ذَهَبْتُ – لَا أَذْهَبُ – لَنْ أَذْهَبَ.","w":["لَنْ steht nur mit dem Präsens.","لَا verneint das Präsens.","مَا verneint das Futur nicht."]},
 {"q":"Was verstärkt ein verneintes Futur, was ein verneintes Perfekt?","a":["أَبَدًا – قَطُّ","قَطُّ – أَبَدًا","جِدًّا – فَقَطْ","beide mit أَبَدًا"],"e":"لَنْ أَشْرَبَهُ أَبَدًا – مَا رَأَيْتُهُ قَطُّ.","w":["Genau umgekehrt.","جِدًّا = sehr, فَقَطْ = nur.","Beim Perfekt steht قَطُّ."]}
],
"b2-20": [
 {"q":"Welche Endungen hat der Dual?","a":["Nominativ -āni, Akkusativ und Genitiv -aini","Nominativ -aini, sonst -āni","immer -āni","Nominativ -ūna, sonst -īna"],"e":"رِيَالَانِ – رِيَالَيْنِ.","w":["Genau umgekehrt.","-āni nur im Nominativ.","Das ist der männliche Plural."]},
 {"q":"Warum heißt es اشْتَرَيْتُهُ بِرِيَالَيْنِ?","a":["Nach der Präposition بِـ steht der Genitiv: -aini.","Weil es Objekt ist.","Weil es Plural ist.","Weil es bestimmt ist."],"e":"Genitiv Dual = -aini.","w":["Das Objekt ist ـهُ.","Es ist Dual.","Es ist unbestimmt."]},
 {"q":"Warum fällt das nūn in أَلْفَا رِيَالٍ weg?","a":["Der Dual ist hier Muḍāf; vor dem Muḍāf ilaihi fällt das nūn weg.","Weil أَلْف weiblich ist.","Weil es Akkusativ ist.","Das ist ein Fehler."],"e":"أَلْفَانِ → أَلْفَا رِيَالٍ.","w":["أَلْف ist männlich.","Es ist Nominativ.","Das ist die Regel."]}
],
"b2-21": [
 {"q":"Welche zwei Wirkungen hat لَمْ?","a":["Es verneint in der Vergangenheit und setzt den Jussiv.","Es verneint die Zukunft und setzt den Subjunktiv.","Es fragt und setzt den Indikativ.","Es verbietet und setzt den Subjunktiv."],"e":"يَذْهَبُ → لَمْ يَذْهَبْ „er ging nicht“.","w":["Das ist لَنْ.","لَمْ fragt nicht.","Verbieten tut لَا mit Jussiv."]},
 {"q":"Was ist der Unterschied zwischen مَا ذَهَبَ und لَمْ يَذْهَبْ?","a":["Beide heißen „er ging nicht“; لَمْ steht mit dem Jussiv-Präsens.","مَا ذَهَبَ heißt „er geht nicht“.","لَمْ يَذْهَبْ heißt „er wird nicht gehen“.","لَمْ يَذْهَبْ ist ein Verbot."],"e":"Zwei Wege, die Vergangenheit zu verneinen.","w":["مَا mit Perfekt ist Vergangenheit.","Das wäre لَنْ يَذْهَبَ.","Ein Verbot wäre لَا تَذْهَبْ."]},
 {"q":"Welche drei Wortarten kennt die arabische Grammatik?","a":["Nomen (ism), Verb (fiʿl), Partikel (ḥarf)","Nomen, Adjektiv, Verb","Verb, Adverb, Präposition","Subjekt, Prädikat, Objekt"],"e":"Adjektive und Adverbien zählen zu den Nomen.","w":["Adjektive gehören zu den Nomen.","Adverbien sind Nomen; Präpositionen Partikeln.","Das sind Satzteile, keine Wortarten."]}
],
"b2-22": [
 {"q":"Welche Partikel setzt welchen Modus?","a":["أَنْ/لَنْ → Subjunktiv; لَمْ/لَا (Verbot) → Jussiv","أَنْ/لَنْ → Jussiv; لَمْ → Subjunktiv","alle → Subjunktiv","keine Partikel ändert den Modus"],"e":"Ohne Partikel: Indikativ.","w":["Genau umgekehrt.","لَمْ setzt den Jussiv.","Doch: sie ändern die Endung."]},
 {"q":"Woran erkennt man bei تَذْهَبُونَ Subjunktiv oder Jussiv?","a":["Das nūn fällt weg: تَذْهَبُوا","Es bekommt Fatḥa: تَذْهَبُونَا","Es bekommt Sukūn: تَذْهَبُونْ","Es ändert sich nicht."],"e":"Bei den fünf Verben ist der Wegfall des nūn das Zeichen.","w":["Ein Alif wird nicht angehängt.","Das nūn fällt ganz weg.","Es ändert sich: das nūn fällt."]},
 {"q":"Warum sehen أَنْ تَذْهَبِي und لَا تَذْهَبِي gleich aus?","a":["Bei den fünf Verben verlieren Subjunktiv und Jussiv beide das nūn.","Weil beide Verbote sind.","Weil beide Indikativ sind.","Das ist Zufall."],"e":"Man erkennt den Modus an der Partikel davor.","w":["أَنْ تَذْهَبِي ist kein Verbot.","Ohne nūn ist es kein Indikativ.","Es ist eine Regel."]}
],
"b2-23": [
 {"q":"Warum heißt es رَأَيْتُ الْمُدَرِّسِينَ mit -īna?","a":["Der männliche Plural hat im Akkusativ und Genitiv -īna.","Weil es Dual ist.","Weil es weiblich ist.","Weil es bestimmt ist."],"e":"Nominativ -ūna, sonst -īna.","w":["Der Dual hätte -aini.","Es ist männlich.","Der Artikel ändert die Endung nicht."]},
 {"q":"Was passiert mit dem nūn von مُدَرِّسُونَ als Muḍāf?","a":["Es fällt weg: مُدَرِّسُو الْمَدْرَسَةِ","Es bleibt: مُدَرِّسُونَ الْمَدْرَسَةِ","Es wird zu ي: مُدَرِّسِي","Es bekommt Tanwīn."],"e":"Wie beim Dual fällt das nūn vor dem Muḍāf ilaihi weg.","w":["Vor dem Muḍāf ilaihi fällt das nūn weg.","مُدَرِّسِي wäre Genitiv/Akkusativ bzw. „mein Lehrer“.","Der Plural auf -ūna hat kein Tanwīn."]},
 {"q":"Wie werden die Zehner (عِشْرُونَ …) dekliniert?","a":["wie der männliche Plural: -ūna / -īna","wie der Dual: -āni / -aini","gar nicht","wie ein Diptoton"],"e":"عِشْرُونَ (Nom.), عِشْرِينَ (Akk./Gen.).","w":["Sie haben Plural-, keine Dualendungen.","Sie verändern sich je nach Fall.","Sie haben die Endungen des gesunden Plurals."]}
],
"b2-24": [
 {"q":"Welche Zahlen haben das umgekehrte Geschlecht des Gezählten?","a":["3–10 (und der Einer bei 13–19)","1 und 2","20–90","100 und 1000"],"e":"ثَلَاثَةُ رِجَالٍ – ثَلَاثُ نِسَاءٍ.","w":["1 und 2 stimmen überein.","Die Zehner bleiben gleich.","مِائَةٌ und أَلْفٌ bleiben gleich."]},
 {"q":"In welcher Form steht das Gezählte nach 100?","a":["Singular im Genitiv","Plural im Genitiv","Singular im Akkusativ","Dual"],"e":"مِائَةُ طَالِبٍ.","w":["Das gilt für 3–10.","Das gilt für 11–99.","Nach 100 steht kein Dual."]},
 {"q":"Warum heißt es اثْنَيْ عَشَرَ in أُرِيدُ اثْنَيْ عَشَرَ رِيَالًا?","a":["Der erste Teil von 12 wird wie ein Dual dekliniert: Akkusativ اثْنَيْ.","Weil 12 immer so heißt.","Weil رِيَالًا Plural ist.","Das ist ein Fehler."],"e":"Nominativ اثْنَا عَشَرَ, sonst اثْنَيْ عَشَرَ.","w":["Im Nominativ heißt es اثْنَا.","رِيَالًا ist Singular.","Das ist die Regel."]}
],
"b2-25": [
 {"q":"Welche Rolle hat بَارِدًا in كَانَ الْمَاءُ بَارِدًا?","a":["Khabar von كَانَ (manṣūb)","Objekt","Ḥāl","Ism von كَانَ"],"e":"كَانَ: Ism marfūʿ, Khabar manṣūb.","w":["كَانَ hat kein Objekt.","Es ist die Aussage des Satzes.","Der Ism ist الْمَاءُ."]},
 {"q":"Was bedeutet لَا يَزَالُ?","a":["immer noch","nicht mehr","niemals","noch nicht"],"e":"لَا يَزَالُ بِلَالٌ مَرِيضًا – „Bilāl ist immer noch krank.“","w":["„nicht mehr“ wäre لَمْ يَعُدْ.","„niemals“ ist أَبَدًا.","„noch nicht“ ist لَمَّا / لَمْ … بَعْدُ."]},
 {"q":"Welche Formen hat أَبٌ als Muḍāf in den drei Fällen?","a":["أَبُو – أَبَا – أَبِي","أَبُ – أَبَ – أَبِ","أَبُو in allen Fällen","أَبِي – أَبَا – أَبُو"],"e":"هَذَا أَبُوكَ – رَأَيْتُ أَبَاكَ – مَعَ أَبِيكَ.","w":["Die fünf Nomen haben lange Vokale.","Sie ändern sich je nach Fall.","Die Reihenfolge ist falsch."]}
],
"b2-26": [
 {"q":"Wie heißen die drei Radikale nach dem Musterverb فَعَلَ?","a":["fāʾ, ʿain, lām","alif, bāʾ, tāʾ","mīm, nūn, wāw","ḥāʾ, ḫāʾ, dāl"],"e":"Deshalb: schwach am fāʾ = Mithāl, am ʿain = Ajwaf, am lām = Nāqiṣ.","w":["Das sind die ersten Buchstaben des Alphabets.","Das sind beliebige Buchstaben.","Das sind beliebige Buchstaben."]},
 {"q":"Was passiert beim Mithāl وَزَنَ im Präsens?","a":["Das و fällt weg: يَزِنُ","Das و wird zu ي: يَيْزِنُ","Es bleibt: يَوْزِنُ","Es wird verdoppelt."],"e":"وَجَدَ يَجِدُ، وَصَلَ يَصِلُ، وَقَفَ يَقِفُ.","w":["Es wird nicht zu ي.","Das و fällt weg.","Es wird nicht verdoppelt."]},
 {"q":"Was drückt der Diminutiv (فُعَيْلٌ) aus?","a":["etwas Kleines oder Liebes: نُهَيْرٌ „Bächlein“","den Plural","das Weibliche","den Komparativ"],"e":"وَلَدٌ → وُلَيْدٌ, نَهْرٌ → نُهَيْرٌ.","w":["Es ist kein Plural.","Das Weibliche zeigt meist ة.","Der Komparativ ist أَفْعَلُ."]}
],
"b2-27": [
 {"q":"Warum heißt es قُلْتُ und nicht قَالْتُ?","a":["Vor einer Endung mit Konsonant fällt der schwache zweite Radikal weg.","Weil قَالَ weiblich ist.","Weil es Präsens ist.","Das ist Dialekt."],"e":"قَالَ → قُلْتُ (u, weil يَقُولُ); سَارَ → سِرْتُ (i, weil يَسِيرُ).","w":["Das Geschlecht spielt keine Rolle.","Es ist Perfekt.","Das ist Hochsprache."]},
 {"q":"Warum heißt es لَمْ يَقُلْ ohne و?","a":["Im Jussiv träfen zwei Sukūn aufeinander; das و fällt weg.","Weil لَمْ das و verbietet.","Weil es Perfekt ist.","Das ist ein Fehler."],"e":"يَقُولُ → لَمْ يَقُولْ → لَمْ يَقُلْ.","w":["Es liegt an der Lautregel, nicht an لَمْ selbst.","Es ist Präsens (Jussiv).","Das ist die Regel."]},
 {"q":"Welche zwei Objekte hat ظَنَّ in أَظُنُّ الْجَوَّ جَمِيلًا?","a":["الْجَوَّ und جَمِيلًا – beide im Akkusativ","nur الْجَوَّ","nur جَمِيلًا","keine"],"e":"ظَنَّ macht aus einem Nominalsatz zwei Objekte.","w":["Auch جَمِيلًا ist Objekt.","Auch الْجَوَّ ist Objekt.","ظَنَّ hat zwei Objekte."]}
],
"b2-28": [
 {"q":"Warum schreibt man دَعَا mit ا, aber بَكَى mit ى?","a":["Wurzel mit و → ا, Wurzel mit ي → ى","Weil بَكَى weiblich ist.","Weil دَعَا Präsens ist.","Das ist beliebig."],"e":"دعو → دَعَا; بكي → بَكَى.","w":["Das Geschlecht spielt keine Rolle.","Beide sind Perfekt.","Die Wurzel bestimmt die Schreibung."]},
 {"q":"Was ist das Jussivzeichen bei يَدْعُو nach لَمْ?","a":["Der schwache Buchstabe fällt weg: لَمْ يَدْعُ","Sukūn: لَمْ يَدْعُوْ","Fatḥa: لَمْ يَدْعُوَ","Das nūn fällt weg."],"e":"Bei Nāqiṣ-Verben: Wegfall des schwachen Buchstabens.","w":["Auf dem و bleibt kein Sukūn stehen; es fällt weg.","Fatḥa ist der Subjunktiv.","يَدْعُو hat kein nūn."]},
 {"q":"Warum ist die Fatḥa in لَنْ يَنْسَى nur „gedacht“?","a":["Auf einem Alif (ى) kann man keinen Vokal sprechen.","Weil لَنْ keine Wirkung hat.","Weil يَنْسَى Perfekt ist.","Weil es weiblich ist."],"e":"Man sagt: مَنْصُوبٌ بِفَتْحَةٍ مُقَدَّرَةٍ.","w":["لَنْ wirkt: das Verb ist manṣūb.","يَنْسَى ist Präsens.","Das Geschlecht spielt keine Rolle."]}
],
"b2-29": [
 {"q":"Warum heißt es حَجَجْتُ, aber حَجَّ?","a":["Vor Endungen mit Konsonant werden die zwei gleichen Radikale getrennt.","Weil حَجَجْتُ weiblich ist.","Weil حَجَّ Präsens ist.","Das ist beliebig."],"e":"حَجَّ، حَجُّوا – aber حَجَجْتُ، حَجَجْنَا.","w":["حَجَجْتُ heißt „ich pilgerte“.","Beide sind Perfekt.","Es gibt eine feste Regel."]},
 {"q":"Was bedeutet لَمَّا mit dem Perfekt?","a":["„als“","„noch nicht“","„warum“","„damit“"],"e":"لَمَّا سَمِعْتُ الْجَرَسَ دَخَلْتُ.","w":["„noch nicht“ heißt لَمَّا mit dem Jussiv.","„warum“ ist لِمَاذَا.","„damit“ ist لِـ / كَيْ."]},
 {"q":"Welche Verbklasse hat ein Hamza als Radikal?","a":["مَهْمُوزٌ","مُضَعَّفٌ","مِثَالٌ","سَالِمٌ"],"e":"أَكَلَ، سَأَلَ، قَرَأَ.","w":["Muḍāʿaf hat zwei gleiche Radikale.","Mithāl hat و/ي als ersten Radikal.","Sālim hat weder Hamza noch schwache Radikale."]}
],
"b2-30": [
 {"q":"Welche Form hat die 1. Person im Dual?","a":["keine eigene; man benutzt den Plural (ذَهَبْنَا)","ذَهَبْنَانِ","ذَهَبْتُمَا","ذَهَبَا"],"e":"„wir zwei“ = „wir“.","w":["Diese Form gibt es nicht.","ذَهَبْتُمَا heißt „ihr beide“.","ذَهَبَا heißt „sie beide“."]},
 {"q":"Warum gehört يَذْهَبَانِ zu den fünf Verben?","a":["Es endet auf nūn, das im Subjunktiv und Jussiv wegfällt.","Weil es fünf Buchstaben hat.","Weil es Plural ist.","Weil es weiblich ist."],"e":"يَذْهَبَانِ، تَذْهَبَانِ، يَذْهَبُونَ، تَذْهَبُونَ، تَذْهَبِينَ.","w":["Die Zahl bezieht sich auf die fünf Formen, nicht auf Buchstaben.","Es ist Dual.","Es ist männlich."]},
 {"q":"Welche Form passt? الطَّالِبَتَانِ … إِلَى الْمَكْتَبَةِ (gingen).","a":["ذَهَبَتَا","ذَهَبَا","ذَهَبْنَ","ذَهَبَتْ"],"e":"3. Person Dual weiblich: ذَهَبَتَا.","w":["ذَهَبَا ist männlich.","ذَهَبْنَ ist Plural.","Nach dem Subjekt richtet sich das Verb in der Zahl: Dual."]}
],
"b2-31": [
 {"q":"In welchen vier Punkten stimmt das Naʿt mit dem Manʿūt überein?","a":["Bestimmtheit, Fall, Zahl, Geschlecht","nur Fall und Geschlecht","Bestimmtheit und Fall","gar nicht"],"e":"مُدَرِّسَانِ جَدِيدَانِ – الْمُدَرِّسَةُ الْجَدِيدَةُ.","w":["Auch Bestimmtheit und Zahl.","Auch Zahl und Geschlecht.","Das Naʿt folgt immer."]},
 {"q":"Warum ist سَهْلٌ in الْكِتَابُ الْجَدِيدُ سَهْلٌ kein Naʿt?","a":["Es ist unbestimmt, das Nomen bestimmt – also Khabar.","Weil es am Ende steht.","Weil es männlich ist.","Doch, es ist ein Naʿt."],"e":"الْجَدِيدُ ist Naʿt (bestimmt), سَهْلٌ Khabar.","w":["Die Stellung allein entscheidet nicht; die Bestimmtheit schon.","Das Geschlecht passt, entscheidet aber nicht.","Ein Naʿt müsste bestimmt sein."]},
 {"q":"Welches Adjektiv passt zu إِخْوَةٌ (Personen, Plural)?","a":["كِبَارٌ","كَبِيرَةٌ","كَبِيرٌ","الْكِبَارُ"],"e":"Personen im Plural → Adjektiv im Plural, unbestimmt.","w":["Weiblicher Singular gilt nur für Sachplurale.","Singular passt nicht zum Plural.","إِخْوَةٌ ist unbestimmt."]}
]
};
