/* English meanings of the Madina vocabulary (key: the German meaning in madina1-*.js / madina2-*.js).
   arabic.js uses them when the language is English; the question ids stay on the German text. */
window.MADINA_EN = {
"Haus": "house",
"Moschee": "mosque",
"Tür": "door",
"Buch": "book",
"Stift": "pen",
"Schlüssel": "key",
"Schreibtisch": "desk",
"Bett": "bed",
"Stuhl": "chair",
"Junge": "boy",
"Student": "student",
"Mann": "man",
"Händler": "merchant",
"Lehrer": "teacher",
"Arzt": "doctor",
"Hund": "dog",
"Katze": "cat",
"Esel": "donkey",
"Pferd": "horse",
"Kamel": "camel",
"Stern": "star",
"Hahn": "rooster",
"Hemd": "shirt",
"Tuch, Taschentuch": "cloth, handkerchief",
"ja": "yes",
"nein": "no",
"was?": "what?",
"wer?": "who?",
"und": "and",
"jenes, das (dort)": "that (over there)",
"Imam": "imam",
"Stein": "stone",
"Zucker": "sugar",
"Milch": "milk",
"reich": "rich",
"arm": "poor",
"lang, groß": "long, tall",
"kurz, klein": "short, small",
"kalt": "cold",
"heiß": "hot",
"sitzend": "sitting",
"stehend": "standing",
"neu": "new",
"alt": "old",
"nah": "near",
"fern": "far",
"sauber": "clean",
"schmutzig": "dirty",
"klein": "small",
"groß": "big",
"leicht (Gewicht)": "light (weight)",
"schwer": "heavy",
"offen": "open",
"kaputt, zerbrochen": "broken",
"schön": "beautiful",
"süß": "sweet",
"krank": "ill",
"das Papier": "the paper",
"das Wasser": "the water",
"der Apfel": "the apple",
"das Geschäft": "the shop",
"die Sonne": "the sun",
"der Mond": "the moon",
"wo?": "where?",
"in": "in",
"auf": "on",
"er, es": "he, it",
"sie, es": "she, it",
"Zimmer": "room",
"der Himmel": "the sky",
"das Badezimmer": "the bathroom",
"das Klassenzimmer": "the classroom",
"die Küche": "the kitchen",
"die Toilette": "the toilet",
"Uhr, Stunde": "clock, hour",
"von, aus": "from",
"nach, zu": "to",
"ich": "I",
"du (m.)": "you (m.)",
"er ging": "he went",
"er ging hinaus": "he went out",
"die Schule": "the school",
"die Universität": "the university",
"der Markt": "the market",
"der Direktor": "the director",
"Japan": "Japan",
"China": "China",
"Indien": "India",
"die Philippinen": "the Philippines",
"unter": "under",
"o! (Anrede)": "O! (address)",
"hier": "here",
"dort": "there",
"der Gesandte": "the Messenger",
"der Onkel (Bruder des Vaters)": "the uncle (father's brother)",
"der Onkel (Bruder der Mutter)": "the uncle (mother's brother)",
"der Sohn": "the son",
"die Tochter, das Mädchen": "the daughter, the girl",
"der Name": "the name",
"die Straße": "the street",
"das Auto": "the car",
"die Kaaba": "the Kaaba",
"geschlossen": "closed",
"die Tasche": "the bag",
"diese, dies (w.)": "this (f.)",
"für, gehört": "for, belongs to",
"auch": "also",
"sehr": "very",
"Bruder": "brother",
"Schwester": "sister",
"der Vater": "the father",
"die Mutter": "the mother",
"Hand (w.)": "hand (f.)",
"Bein, Fuß (w.)": "leg, foot (f.)",
"Auge (w.)": "eye (f.)",
"Ohr (w.)": "ear (f.)",
"Kopf": "head",
"Nase": "nose",
"Mund": "mouth",
"Gesicht": "face",
"das Bügeleisen": "the iron (for clothes)",
"die Kuh": "the cow",
"das Fahrrad": "the bicycle",
"der Löffel": "the spoon",
"der Bauer": "the farmer",
"der Kühlschrank": "the refrigerator",
"der Tee": "the tea",
"der Kaffee": "the coffee",
"der Kochtopf (w.)": "the cooking pot (f.)",
"das Fenster": "the window",
"schnell": "fast",
"der Osten": "the east",
"der Westen": "the west",
"jene (w.)": "that (f.)",
"die Kamelstute": "the she-camel",
"die Ente": "the duck",
"die Krankenschwester": "the nurse",
"das Ei": "the egg",
"der Muezzin": "the muezzin",
"die Henne": "the hen",
"hinter": "behind",
"vor (örtlich)": "in front of",
"er saß, setzte sich": "he sat, sat down",
"Ingenieur": "engineer",
"Präsident, Leiter": "president, head",
"das Messer": "the knife",
"das Krankenhaus": "the hospital",
"Amerika": "America",
"Deutschland": "Germany",
"England": "England",
"der Irak": "Iraq",
"die Schweiz": "Switzerland",
"der, welcher (Relativ, m.)": "who, which (relative, m.)",
"bei": "at, with",
"jetzt": "now",
"heute": "today",
"warum?": "why?",
"faul": "lazy",
"hungrig": "hungry",
"durstig": "thirsty",
"zornig": "angry",
"voll": "full",
"leicht, einfach": "easy",
"schwierig": "difficult",
"fleißig": "hard-working",
"berühmt": "famous",
"die Sprache": "the language",
"Arabisch (die Sprache)": "Arabic (the language)",
"Englisch (die Sprache)": "English (the language)",
"die Stadt": "the city",
"Kairo": "Cairo",
"das Obst": "the fruit",
"der Vogel": "the bird",
"der Spatz": "the sparrow",
"der Becher": "the cup",
"die Bibliothek, der Buchladen": "the library, the bookshop",
"der Minister": "the minister",
"scharf": "sharp",
"die Klinik": "the clinic",
"der Ventilator": "the fan",
"Kuwait": "Kuwait",
"Indonesien": "Indonesia",
"mit": "with",
"in, an, mit": "in, at, with",
"du (m.) gingst": "you (m.) went",
"ich ging": "I went",
"der Kollege, Mitschüler": "the colleague, classmate",
"der junge Mann": "the young man",
"der Ehemann": "the husband",
"das Kind": "the child",
"eins, ein einziger": "one, a single",
"darin (m.)": "in it (m.)",
"darin (w.)": "in it (f.)",
"ich liebe, mag": "I love, I like",
"du (m.) liebst": "you (m.) love",
"was? (vor Verben)": "what? (before verbs)",
"du (w.)": "you (f.)",
"sie ging": "she went",
"sie saß": "she sat",
"die, welche (Relativ, w.)": "who, which (relative, f.)",
"nach (zeitlich)": "after (time)",
"Wie geht es dir?": "How are you?",
"Mir geht es gut.": "I am fine.",
"mein Herr!": "sir!",
"meine Dame!": "madam!",
"die Tante (Schwester des Vaters)": "the aunt (father's sister)",
"die Tante (Schwester der Mutter)": "the aunt (mother's sister)",
"der Baum": "the tree",
"das Heft": "the notebook",
"die junge Frau": "the young woman",
"der Inspektor": "the inspector",
"Syrien": "Syria",
"Malaysia": "Malaysia",
"Gelehrter": "scholar",
"stark": "strong",
"schwach": "weak",
"diese (Pl.)": "these (pl.)",
"jene (Pl.)": "those (pl.)",
"sie (m. Pl.)": "they (m. pl.)",
"sie (w. Pl.)": "they (f. pl.)",
"sie (m.) gingen": "they (m.) went",
"sie (w.) gingen": "they (f.) went",
"einige, ein Teil": "some, a part",
"Muslim": "Muslim",
"Muslimin": "Muslim woman",
"Freund": "friend",
"Berg": "mountain",
"Gast": "guest",
"alter Mann, Gelehrter": "old man, scholar",
"Pilger": "pilgrim",
"Dorf": "village",
"Feld": "field",
"die Leute": "the people",
"das Restaurant": "the restaurant",
"Professor, Lehrer": "professor, teacher",
"Professorin": "professor (f.)",
"die Frau": "the woman",
"Ehefrau": "wife",
"ihr (m. Pl.)": "you (m. pl.)",
"wir": "we",
"ihr gingt": "you went (pl.)",
"wir gingen": "we went",
"welcher?": "which?",
"herzlich willkommen!": "welcome!",
"der Herr": "the Lord",
"die Religion": "the religion",
"der Prophet": "the prophet",
"die Gebetsrichtung": "the direction of prayer",
"der Flughafen": "the airport",
"das Gericht": "the court",
"die Fakultät": "the faculty",
"der Garten": "the garden",
"der Monat": "the month",
"Samstag": "Saturday",
"Enkel": "grandson",
"Christ": "Christian",
"Griechenland": "Greece",
"die Verfassung": "the constitution",
"ihr (w. Pl.)": "you (f. pl.)",
"ihr (w.) gingt": "you (f. pl.) went",
"vor (zeitlich)": "before (time)",
"er kehrte zurück": "he returned",
"das Gebet": "the prayer",
"der Gebetsruf": "the call to prayer",
"die Lektion, Unterrichtsstunde": "the lesson, class period",
"die Woche": "the week",
"die Prüfung": "the examination",
"der Fluss": "the river",
"das Meer": "the sea",
"das Hotel": "the hotel",
"das Flugzeug": "the aeroplane",
"sie ging hinaus": "she went out",
"die Firma": "the company",
"der Direktor der Firma": "the director of the company",
"der Direktor, Leiter": "the director, head",
"billig": "cheap",
"japanisch": "Japanese",
"das Hemd": "the shirt",
"das Rad": "the wheel",
"die (Schreib-)Tafel": "the (black)board",
"das Fest": "the feast",
"der Riyal": "the riyal",
"das Jahr": "the year",
"der Stadtteil": "the district",
"die Rakʿa (Gebetseinheit)": "the rakʿa (unit of prayer)",
"das Lineal": "the ruler",
"wie viel(e)?": "how much, how many?",
"sie beide": "they both",
"diese beiden (m.)": "these two (m.)",
"diese beiden (w.)": "these two (f.)",
"Hand": "hand",
"eins": "one",
"zwei": "two",
"drei": "three",
"vier": "four",
"fünf": "five",
"sechs": "six",
"sieben": "seven",
"acht": "eight",
"neun": "nine",
"zehn": "ten",
"alle, jeder": "all, every",
"sie alle": "all of them",
"ihr alle": "all of you",
"wir alle": "all of us",
"danke": "thank you",
"der Tag": "the day",
"der Preis": "the price",
"die Hälfte": "the half",
"das Land": "the country",
"der Qirsch (kleine Münze)": "the qirsh (small coin)",
"unterschiedlich": "different",
"der Bus": "the bus",
"der Fahrgast": "the passenger",
"von ihnen": "of them",
"die Frage": "the question",
"Europa": "Europe",
"die (Hosen-/Jacken-)Tasche": "the pocket",
"Jugoslawien": "Yugoslavia",
"eins (w.)": "one (f.)",
"zwei (w.)": "two (f.)",
"Wort": "word",
"Zeitschrift": "magazine",
"Lektion": "lesson",
"Buchstabe": "letter (of the alphabet)",
"Onkel (väterlicherseits)": "uncle (father's side)",
"Tochter, Mädchen": "daughter, girl",
"Sohn": "son",
"Frau": "woman",
"jener (= ذَلِكَ)": "that (= ذَلِكَ)",
"die Farbe": "the colour",
"geräumig, weit": "spacious, wide",
"wir lieben": "we love",
"wir lieben ihn": "we love him",
"Asien": "Asia",
"rot": "red",
"blau": "blue",
"grün": "green",
"schwarz": "black",
"gelb": "yellow",
"weiß": "white",
"Bagdad": "Baghdad",
"Dschidda": "Jeddah",
"Teetasse": "teacup",
"Minute": "minute",
"Taschentuch": "handkerchief",
"er sagte": "he said",
"sie sagte": "she said",
"Istanbul": "Istanbul",
"Washington": "Washington",
"Taif (Stadt)": "Taif (city)",
"Klassenkamerad, Kollege": "classmate, colleague",
"Hotel": "hotel",
"intelligent": "intelligent",
"dumm": "stupid",
"Anstand, Charakter": "manners, character",
"verheiratet": "married",
"unverheiratet": "unmarried",
"Jude": "Jew",
"Wörterbuch": "dictionary",
"Dollar": "dollar",
"hundert": "hundred",
"tausend": "thousand",
"Rupie": "rupee",
"Seite (eines Buches)": "page (of a book)",
"einer, der die Prüfung bestanden hat": "one who passed the exam",
"teuer": "expensive",
"Ärmel": "sleeve",
"Anwalt": "lawyer",
"Richter": "judge",
"Tal": "valley",
"Treffen": "meeting",
"froh, erfreut": "glad, pleased",
"gut": "good",
"(Hosen-, Jacken-)Tasche": "pocket (trousers, jacket)",
"Fluss": "river",
"Telegramm": "telegram",
"Bank (Geldinstitut)": "bank (money)",
"Postamt": "post office",
"ist nicht": "is not",
"Brüder": "brothers",
"Unterkunft, Schlafraum": "lodging, dormitory",
"Team, Mannschaft": "team",
"im Traum": "in a dream",
"Alter; Zahn": "age; tooth",
"Spieler": "player",
"faul (m.; f. كَسْلَى)": "lazy (m.; f. كَسْلَى)",
"Vollbruder (gleicher Vater und gleiche Mutter)": "full brother (same father and mother)",
"Fenster": "window",
"Monat": "month",
"Preis": "price",
"erster (f. أُولَى)": "first (f. أُولَى)",
"doch (bejahende Antwort auf eine verneinte Frage)": "yes indeed (answer to a negative question)",
"welcher von beiden?": "which of the two?",
"Möge dich kein Unheil treffen! / Keine Sorge!": "no harm! / don't worry!",
"Tee": "tea",
"weil": "because",
"Krankenhaus": "hospital",
"Weintrauben": "grapes",
"Bananen": "bananas",
"Feigen": "figs",
"Morgendämmerung": "dawn",
"Antwort": "answer",
"Frage": "question",
"Schlange": "snake",
"Lebensmittelhändler": "grocer",
"Stock": "stick",
"Kaffee": "coffee",
"Geschäft, Laden": "shop, store",
"Tafel": "board",
"zerbrechen": "to break",
"hören": "to hear",
"verstehen": "to understand",
"trinken": "to drink",
"auswendig lernen": "to memorise",
"schlagen": "to hit",
"eintreten": "to enter",
"essen": "to eat",
"waschen": "to wash",
"töten": "to kill",
"Brot": "bread",
"gut (Adverb)": "well (adverb)",
"Gebäude": "building",
"Sure": "sura",
"Wohnung": "flat, apartment",
"O mein Söhnchen!": "O my little son!",
"nur": "only",
"bügeln": "to iron",
"Ich habe es gut verstanden.": "I understood it well.",
"Möge Allah dein Wissen vermehren.": "May Allah increase your knowledge.",
"Diener": "servant",
"„Was Allah will“ – Ausruf des Staunens": "“What Allah wills” – expression of wonder",
"Fahrgast (Bus, Zug, Flugzeug)": "passenger (bus, train, plane)",
"sich freuen, zufrieden sein": "to be glad, pleased",
"kommen": "to come",
"ich glaube, ich nehme an": "I think, I suppose",
"hungrig (f.)": "hungry (f.)",
"müde": "tired",
"gib! bring!": "give! bring!",
"Besen (auch Staubsauger)": "broom (also vacuum cleaner)",
"Brille": "glasses",
"Bild": "picture",
"Seife": "soap",
"Saft": "juice",
"Fußball": "football",
"Treppe": "stairs",
"Rad (vom Auto o. Ä.)": "wheel (of a car etc.)",
"Rundfunk, Radio": "broadcasting, radio",
"gestern Abend": "last night",
"Orange": "orange",
"Basketball": "basketball",
"letzte Woche": "last week",
"Minarett": "minaret",
"Bart": "beard",
"hoch, laut (f. عَالِيَةٌ)": "high, loud (f. عَالِيَةٌ)",
"farbig": "coloured",
"Morgen": "morning",
"halb, Hälfte": "half",
"er ging (zu Fuß)": "he walked",
"nehmen": "to take",
"setzen, stellen, legen": "to put, place, lay",
"finden": "to find",
"suchen": "to look for",
"ein Drittel": "a third",
"Freu dich über die gute Nachricht!": "Rejoice at the good news!",
"Liste": "list",
"Verbindung, Beziehung": "connection, relationship",
"Bedeutung": "meaning",
"Moment": "moment",
"eine Anzahl von Fragen": "a number of questions",
"anwesend sein, teilnehmen": "to be present, attend",
"klingeln": "to ring",
"erschaffen": "to create",
"erheben, hochheben": "to raise, lift",
"Gut gemacht!": "Well done!",
"Schlamm, Lehm": "mud, clay",
"Glocke": "bell",
"Feuer (f.)": "fire (f.)",
"Hauptstadt": "capital city",
"vermischt": "mixed",
"so, auf diese Weise": "thus, in this way",
"Dschinn": "jinn",
"Eisen": "iron",
"so, so wie dies": "like this, thus",
"die (m. Pl., Relativpronomen)": "who (m. pl., relative pronoun)",
"die (f. Pl., Relativpronomen)": "who (f. pl., relative pronoun)",
"immer": "always",
"manchmal": "sometimes",
"noch einmal": "once more",
"Breite": "width",
"Entfernung": "distance",
"Kilometer": "kilometre",
"Zentimeter": "centimetre",
"Meter": "metre",
"arbeiten": "to work",
"Büro": "office",
"Arbeiter": "worker",
"Länge": "length",
"sich im Gebet niederwerfen": "to prostrate in prayer",
"tun, machen": "to do, make",
"reiten, (ein Fahrzeug) besteigen": "to ride, board (a vehicle)",
"zwischen": "between",
"zwischen ihnen beiden": "between the two of them",
"sich im Gebet verbeugen": "to bow in prayer",
"außer; (Uhrzeit) vor": "except; (time) to",
"studieren, lernen": "to study, learn",
"absteigen, herunterkommen": "to get off, come down",
"wissen, kennen": "to know",
"wohnen": "to live (reside)",
"sterben": "to die",
"danken": "to thank",
"hinaufsteigen": "to go up, climb",
"ich vergaß": "I forgot",
"Verwandter, Angehöriger": "relative",
"Station, Bahnhof": "station",
"Friseur": "barber",
"Reis": "rice",
"Anschrift, Adresse": "address",
"Kleidungsstück, Gewand": "garment",
"Klinik, Ambulanz": "clinic, dispensary",
"kommend": "coming",
"Visitenkarte": "business card",
"Brief": "letter",
"Apotheke": "pharmacy",
"Pferde": "horses",
"Eintritt, Eingang": "entry, entrance",
"Ausgang, Hinausgehen": "exit, going out",
"was … betrifft": "as for …",
"Medizin": "medicine",
"Schüler": "pupil",
"Telefon": "telephone",
"Außenminister": "foreign minister",
"Hausaufgaben": "homework",
"Arbeit": "work",
"Nachbar": "neighbour",
"Zahl, Nummer": "number",
"Zeit": "time",
"bezeugen, anwesend sein": "to witness, be present",
"lachen": "to laugh",
"abends": "in the evening",
"jeden Tag": "every day",
"Sonntag": "Sunday",
"Montag": "Monday",
"Dienstag": "Tuesday",
"Mittwoch": "Wednesday",
"Donnerstag": "Thursday",
"Freitag": "Friday",
"Taxi": "taxi",
"Reihe; Klasse": "row; class",
"schließlich": "finally",
"Skorpion (f.)": "scorpion (f.)",
"Schuh": "shoe",
"das Paradies": "Paradise",
"Glas, Becher": "glass, cup",
"Ehepartner": "spouse",
"Blutklumpen": "clot of blood",
"Radioapparat": "radio set",
"Wetter": "weather",
"Fremder": "stranger",
"Rasierapparat": "razor",
"schläfrig": "sleepy",
"dunkel": "dark",
"stark, heftig": "strongly, hard",
"schweigen, ruhig sein": "to be silent, quiet",
"sammeln, versammeln": "to collect, gather",
"kochen": "to cook",
"schneiden": "to cut",
"rasieren": "to shave",
"anbeten, dienen": "to worship, serve",
"wissen": "to know",
"abhalten, verhindern": "to prevent, hinder",
"zurückkehren": "to return",
"ansehen, schauen": "to look at",
"fegen": "to sweep",
"ich weiß nicht": "I don't know",
"Stärke": "strength",
"Blatt Papier": "sheet of paper",
"Sitz": "seat",
"während": "during",
"O mein Vater!": "O my father!",
"lügen": "to lie (tell lies)",
"weinen": "to weep",
"umkippen, sich überschlagen": "to overturn",
"der Weg": "the way",
"beinahe, fast (etwas tun)": "almost (to do something)",
"Exemplar des Qurʾān": "copy of the Qurʾān",
"Linie": "line",
"Exemplar, Muster": "specimen, model",
"Ding, etwas": "thing, something",
"(noch) ein anderer (f. أُخْرَى)": "another (f. أُخْرَى)",
"liniert": "lined",
"kaufen": "to buy",
"Kreide": "chalk",
"Gemeinde": "municipality",
"Halwa (Süßigkeit aus Sesam)": "halwa (sesame sweet)",
"Stoff, Tuch": "cloth, fabric",
"eng": "narrow",
"braun": "brown",
"abwesend sein": "to be absent",
"Ordner (für Papiere)": "file (for papers)",
"Blume": "flower",
"Saturn": "Saturn",
"wollen": "to want",
"nicht-, un-, außer": "non-, un-, other than",
"weiß (f. بَيْضَاءُ)": "white (f. بَيْضَاءُ)",
"schwarz (f. سَوْدَاءُ)": "black (f. سَوْدَاءُ)",
"rot (f. حَمْرَاءُ)": "red (f. حَمْرَاءُ)",
"grün (f. خَضْرَاءُ)": "green (f. خَضْرَاءُ)",
"blau (f. زَرْقَاءُ)": "blue (f. زَرْقَاءُ)",
"Feiertag, Ferien": "holiday",
"nächstes Jahr": "next year",
"die Fliegen": "the flies",
"Ägypten": "Egypt",
"Ruhe": "calm, quiet",
"ruhig, leise (Adverb)": "quietly (adverb)",
"Ankündigung, Werbung": "announcement, advertisement",
"Leute, Familie": "people, family",
"(Brief-)Umschlag": "envelope",
"der Sommer": "the summer",
"der Frühling": "the spring",
"der Herbst": "the autumn",
"der Winter": "the winter",
"Abendessen": "dinner",
"Behandlung": "treatment",
"ich bitte (um)": "I ask (for), please",
"spucken": "to spit",
"Luft": "air",
"besuchen": "to visit",
"erlauben": "to allow",
"beginnen": "to begin",
"möglich sein": "to be possible",
"bleiben": "to remain",
"bitten, hoffen": "to ask, hope",
"der Lärm": "the noise",
"seit": "since",
"Gewohnheit": "habit",
"Museum": "museum",
"Schachtel, Dose": "box, tin",
"Kleidungsstücke": "clothes",
"Herr": "master, Mr",
"Sommerferien": "summer holidays",
"Zoo": "zoo",
"wie, gleich": "like, similar",
"alle, ganz": "all, whole",
"o (vor Wörtern mit Artikel)": "O (before words with the article)",
"Komm, lass uns gehen!": "Come, let's go!",
"Erhöre (mein Gebet)!": "Accept (my prayer)!",
"Pfui! (Überdruss)": "Ugh! (weariness)",
"Bleistift": "pencil",
"Schlafzimmer": "bedroom",
"Nachrichten": "news",
"Tut mir leid, Entschuldigung": "Sorry, excuse me",
"Botschaft": "embassy",
"Jahr": "year",
"Inder": "Indian",
"Wein": "wine",
"vorhanden": "present, existing",
"Seide": "silk",
"Welt, Diesseits": "world, this life",
"Zukunft": "future",
"niemals": "never",
"Anfang": "beginning",
"irgendjemand": "anyone",
"sich anziehen, sich kleiden": "to put on clothes, dress",
"geduldig sein": "to be patient",
"aufgeben, verlassen, lassen": "to give up, leave, let",
"die ʿUmra vollziehen": "to perform ʿumra",
"ʿUmra": "ʿumra",
"das Jenseits": "the Hereafter",
"nicht (Verneinung des Futurs)": "not (negation of the future)",
"nie (in der Vergangenheit)": "never (in the past)",
"Heuchler (wörtl. mit zwei Gesichtern)": "hypocrite (lit. two-faced)",
"Kamm": "comb",
"Kissen": "pillow",
"Knopf": "button",
"Spiegel": "mirror",
"Dieb": "thief",
"die Biographie des Propheten ﷺ": "the biography of the Prophet ﷺ",
"nützlich": "useful",
"Tafsīr, Qurʾān-Erklärung": "tafsīr, exegesis of the Qurʾān",
"schlachten": "to slaughter",
"erklären": "to explain",
"Pfund (Währung)": "pound (currency)",
"einer von beiden": "one of the two (m.)",
"eine von beiden": "one of the two (f.)",
"Empfang": "reception",
"Unterschied": "difference",
"Beispiel": "example",
"langsam, nicht so schnell!": "slowly, not so fast!",
"Mach es dir bequem! Ruh dich aus!": "Make yourself comfortable! Rest!",
"welche (f. Pl.) = اللَّاتِي": "who (f. pl.) = اللَّاتِي",
"verboten": "forbidden",
"teilnehmen an, anwesend sein": "to attend, be present",
"nicht (verneint das Perfekt über den Muḍāriʿ)": "not (negates the past with the muḍāriʿ)",
"noch nicht": "not yet",
"Kühlschrank": "refrigerator",
"Qirsch (kleine Münze)": "qirsh (small coin)",
"Versammlung": "meeting, assembly",
"Geschichte, Erzählung": "story",
"Prophet": "prophet",
"Sekunde": "second",
"Preis (Auszeichnung)": "prize",
"Halle, Saal": "hall",
"eine Prüfung bestehen": "to pass an exam",
"durchfallen (in einer Prüfung)": "to fail (an exam)",
"Familie": "family",
"Bauer": "farmer",
"zwanzig": "twenty",
"dreißig": "thirty",
"vierzig": "forty",
"fünfzig": "fifty",
"sechzig": "sixty",
"siebzig": "seventy",
"achtzig": "eighty",
"neunzig": "ninety",
"zweihundert": "two hundred",
"zweitausend": "two thousand",
"Tausende (Pl. von أَلْفٌ)": "thousands (pl. of أَلْفٌ)",
"dreihundert": "three hundred",
"Gehalt": "salary",
"Lohn": "wage",
"Botschafter": "ambassador",
"Inspektor": "inspector",
"Polizist": "policeman",
"Dekan, Schuldirektor": "dean, headmaster",
"pensioniert, im Ruhestand": "retired",
"alle Teile der Welt": "all parts of the world",
"ein Buch verfassen": "to write a book",
"er ist immer noch": "he is still",
"vorher, früher": "before, previously",
"danach, hinterher": "afterwards",
"getötet": "killed",
"gefangen, Gefangener": "captive, prisoner",
"verwundet": "wounded",
"Fremder, Ausländer": "foreigner",
"Geldbörse": "purse, wallet",
"Bargeld": "cash",
"Ticket, Fahrkarte": "ticket",
"Flugticket hin und zurück": "return air ticket",
"Kilogramm": "kilogram",
"weiblich": "female",
"männlich": "male",
"regelmäßig": "regularly",
"Fehler": "mistake",
"Rückkehr": "return",
"Gehen, Hinweg": "going, outward journey",
"er will": "he wants",
"heftig, stark, schwer": "severe, strong, hard",
"geliebt, Liebling": "beloved, darling",
"schlucken": "to swallow",
"hinken": "to limp",
"notwendig sein": "to be necessary",
"ankommen": "to arrive",
"wiegen": "to weigh",
"versprechen": "to promise",
"anhalten, stehen bleiben": "to stop, stand still",
"schenken": "to give (as a gift)",
"weniger": "less",
"sagen": "to say",
"sein": "to be",
"aufstehen": "to stand up",
"schmecken, kosten": "to taste",
"umrunden, den Ṭawāf machen": "to go round, perform ṭawāf",
"gehen, reisen": "to go, travel",
"leben": "to live",
"abmessen, (ab)wiegen": "to measure, weigh out",
"schlafen": "to sleep",
"fürchten, Angst haben": "to fear, be afraid",
"aufhören (in لَا يَزَالُ: immer noch)": "to cease (in لَا يَزَالُ: still)",
"besiegen, überwältigen": "to defeat, overcome",
"vollständig": "complete",
"Salz": "salt",
"Linsen": "lentils",
"fasten": "to fast",
"sich drehen": "to turn",
"bereuen, umkehren": "to repent, turn back",
"urinieren": "to urinate",
"verkaufen": "to sell",
"Mitternacht": "midnight",
"Kopfschmerz": "headache",
"Öl": "oil",
"Dampf": "steam",
"beschäftigt": "busy",
"Käse": "cheese",
"Ei": "egg",
"Obsthändler": "fruit seller",
"Mehl": "flour",
"Wald": "forest",
"Mittagessen": "lunch",
"Zug": "train",
"es gehört sich nicht": "it is not proper",
"(zu Fuß) gehen": "to walk",
"laufen, rennen": "to run",
"werfen": "to throw",
"zusammenfalten": "to fold",
"führen, rechtleiten": "to guide",
"einladen; beten, rufen": "to invite; to pray, call",
"sich beschweren": "to complain",
"rezitieren, vortragen": "to recite",
"ausradieren": "to erase",
"vergeben": "to forgive",
"vergessen": "to forget",
"fürchten": "to fear",
"folgen": "to follow",
"fallen": "to fall",
"Müll": "rubbish",
"zu trinken geben, gießen": "to give to drink, water",
"bauen": "to build",
"Tag (Tageszeit)": "day(time)",
"rechte Hand, rechts": "right hand, right",
"linke Hand, links": "left hand, left",
"Einnehmen, Essen": "taking, eating",
"Gott": "god",
"Volk": "people, nation",
"Nacht": "night",
"Staub, Erde": "dust, earth",
"zerrissen": "torn",
"Geschenk": "gift",
"Leute, Gefährten": "people, companions",
"Untersuchung, Nachforschung": "investigation",
"Zeig mir!": "Show me!",
"die Pilgerfahrt vollziehen": "to perform the Hajj",
"denken, meinen": "to think, suppose",
"ziehen": "to pull",
"zählen": "to count",
"beschimpfen": "to insult",
"antworten, zurückgeben": "to answer, give back",
"(aus)schütten": "to pour (out)",
"versperren": "to block",
"riechen": "to smell",
"berühren": "to touch",
"stoßen; bezahlen": "to push; to pay",
"krank werden": "to fall ill",
"Mal": "time (occurrence)",
"Handfläche": "palm of the hand",
"traurig sein": "to be sad",
"vorbeigehen": "to pass by",
"unachtsam": "careless",
"Seidenbrokat": "silk brocade",
"Geruch": "smell",
"unangenehm": "unpleasant",
"weich": "soft",
"Kopie, Exemplar": "copy",
"eine Weile": "a while",
"Abfluss, Abwasserleitung": "drain, sewer",
"besser, am besten": "better, best",
"mehr": "more",
"wenn, als (mit Muḍāriʿ)": "when (with the muḍāriʿ)",
"Zwillinge": "twins",
"Ähnlichkeit": "resemblance",
"Fluglinien": "airlines",
"Büro der Fluggesellschaft": "airline office",
"Institut": "institute",
"zwei andere (f. Dual)": "two others (f. dual)",
"Kindheit": "childhood",
"Unterrichtsstunde, Anteil": "class period, share",
"vorgeschriebene Lehrbücher": "set textbooks",
"Krankenbesuch": "visiting the sick",
"Möge Allah dir Erfolg schenken.": "May Allah grant you success.",
"ihr beide": "you two",
"zeigen, hinweisen, empfehlen": "to show, point out, recommend",
"in der Mitte, gemäßigt": "in the middle, moderate",
"al-Muʿjam al-Wasīṭ (arabisches Wörterbuch)": "al-Muʿjam al-Wasīṭ (Arabic dictionary)",
"Stadtviertel": "quarter (of a city)",
"aufhören, zu Ende gehen": "to end, come to an end",
"Adjektiv (Grammatik)": "adjective (grammar)",
"das beschriebene Nomen": "the noun described"
};
